package com.ht.court.model;

import java.util.Date;
import java.util.List;

import org.codehaus.jackson.map.annotate.JsonDeserialize;
import org.codehaus.jackson.map.annotate.JsonSerialize;

import com.hx.HxModel;
import com.hx.common.CustomDateDeserializer;
import com.hx.common.CustomDateSerializer;

public class CourtCasePlan extends HxModel {
  
	private static final long serialVersionUID = -1781963000737542921L;

	private CourtCaseWithBLOBs courtCase;
	
	private String courtName;
	private String caseNum;
	private String caseName;
	private String caseType;
	
	List<CourtTrialRecording> courtTrialRecordings;
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.CASE_ID
     *
     * @mbggenerated
     */
    private String caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.JUDGE_ID
     *
     * @mbggenerated
     */
    private String judgeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.JUDGE_NAME
     *
     * @mbggenerated
     */
    private String judgeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.CLERK_ID
     *
     * @mbggenerated
     */
    private String clerkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.CLERK_NAME
     *
     * @mbggenerated
     */
    private String clerkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.COURT_ID
     *
     * @mbggenerated
     */
    private String courtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.COURT_ROOM_ID
     *
     * @mbggenerated
     */
    private String courtRoomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.COURT_ROOM_NAME
     *
     * @mbggenerated
     */
    private String courtRoomName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.PLAN_START_TIME
     *
     * @mbggenerated
     */
    private Date planStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.PLAN_END_TIME
     *
     * @mbggenerated
     */
    
    private Date planEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.START_TIME
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.REST_TIME
     *
     * @mbggenerated
     */
    private Date restTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.END_TIME
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.ARCH_TIME
     *
     * @mbggenerated
     */
    private Date archTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.TRAIL_STATUS
     *
     * @mbggenerated
     */
    private String trailStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.ACCESS_URL
     *
     * @mbggenerated
     */
    private String accessUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.PUB_ACCESS_URL
     *
     * @mbggenerated
     */
    private String pubAccessUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.VOD_ACCESS_URL
     *
     * @mbggenerated
     */
    private String vodAccessUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.ALLOW_LIVE_FLAG
     *
     * @mbggenerated
     */
    private Byte allowLiveFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.COURT_REC
     *
     * @mbggenerated
     */
    private String courtRec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.BURST_STATUS
     *
     * @mbggenerated
     */
    private Byte burstStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.COLLEGIAL_ID
     *
     * @mbggenerated
     */
    private String collegialId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE_PLAN.TRIAL_LEVEL
     *
     * @mbggenerated
     */
    private String trialLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.CASE_ID
     *
     * @return the value of COURT_CASE_PLAN.CASE_ID
     *
     * @mbggenerated
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.CASE_ID
     *
     * @param caseId the value for COURT_CASE_PLAN.CASE_ID
     *
     * @mbggenerated
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.JUDGE_ID
     *
     * @return the value of COURT_CASE_PLAN.JUDGE_ID
     *
     * @mbggenerated
     */
    public String getJudgeId() {
        return judgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.JUDGE_ID
     *
     * @param judgeId the value for COURT_CASE_PLAN.JUDGE_ID
     *
     * @mbggenerated
     */
    public void setJudgeId(String judgeId) {
        this.judgeId = judgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.JUDGE_NAME
     *
     * @return the value of COURT_CASE_PLAN.JUDGE_NAME
     *
     * @mbggenerated
     */
    public String getJudgeName() {
        return judgeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.JUDGE_NAME
     *
     * @param judgeName the value for COURT_CASE_PLAN.JUDGE_NAME
     *
     * @mbggenerated
     */
    public void setJudgeName(String judgeName) {
        this.judgeName = judgeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.CLERK_ID
     *
     * @return the value of COURT_CASE_PLAN.CLERK_ID
     *
     * @mbggenerated
     */
    public String getClerkId() {
        return clerkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.CLERK_ID
     *
     * @param clerkId the value for COURT_CASE_PLAN.CLERK_ID
     *
     * @mbggenerated
     */
    public void setClerkId(String clerkId) {
        this.clerkId = clerkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.CLERK_NAME
     *
     * @return the value of COURT_CASE_PLAN.CLERK_NAME
     *
     * @mbggenerated
     */
    public String getClerkName() {
        return clerkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.CLERK_NAME
     *
     * @param clerkName the value for COURT_CASE_PLAN.CLERK_NAME
     *
     * @mbggenerated
     */
    public void setClerkName(String clerkName) {
        this.clerkName = clerkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.COURT_ID
     *
     * @return the value of COURT_CASE_PLAN.COURT_ID
     *
     * @mbggenerated
     */
    public String getCourtId() {
        return courtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.COURT_ID
     *
     * @param courtId the value for COURT_CASE_PLAN.COURT_ID
     *
     * @mbggenerated
     */
    public void setCourtId(String courtId) {
        this.courtId = courtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.COURT_ROOM_ID
     *
     * @return the value of COURT_CASE_PLAN.COURT_ROOM_ID
     *
     * @mbggenerated
     */
    public String getCourtRoomId() {
        return courtRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.COURT_ROOM_ID
     *
     * @param courtRoomId the value for COURT_CASE_PLAN.COURT_ROOM_ID
     *
     * @mbggenerated
     */
    public void setCourtRoomId(String courtRoomId) {
        this.courtRoomId = courtRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.COURT_ROOM_NAME
     *
     * @return the value of COURT_CASE_PLAN.COURT_ROOM_NAME
     *
     * @mbggenerated
     */
    public String getCourtRoomName() {
        return courtRoomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.COURT_ROOM_NAME
     *
     * @param courtRoomName the value for COURT_CASE_PLAN.COURT_ROOM_NAME
     *
     * @mbggenerated
     */
    public void setCourtRoomName(String courtRoomName) {
        this.courtRoomName = courtRoomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.PLAN_START_TIME
     *
     * @return the value of COURT_CASE_PLAN.PLAN_START_TIME
     *
     * @mbggenerated
     */
    @JsonSerialize(using = CustomDateSerializer.class)
	@JsonDeserialize(using = CustomDateDeserializer.class)
    public Date getPlanStartTime() {
        return planStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.PLAN_START_TIME
     *
     * @param planStartTime the value for COURT_CASE_PLAN.PLAN_START_TIME
     *
     * @mbggenerated
     */
    
    public void setPlanStartTime(Date planStartTime) {
        this.planStartTime = planStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.PLAN_END_TIME
     *
     * @return the value of COURT_CASE_PLAN.PLAN_END_TIME
     *
     * @mbggenerated
     */
    @JsonSerialize(using = CustomDateSerializer.class)
	@JsonDeserialize(using = CustomDateDeserializer.class)
    public Date getPlanEndTime() {
        return planEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.PLAN_END_TIME
     *
     * @param planEndTime the value for COURT_CASE_PLAN.PLAN_END_TIME
     *
     * @mbggenerated
     */
    public void setPlanEndTime(Date planEndTime) {
        this.planEndTime = planEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.START_TIME
     *
     * @return the value of COURT_CASE_PLAN.START_TIME
     *
     * @mbggenerated
     */
    @JsonSerialize(using = CustomDateSerializer.class)
	@JsonDeserialize(using = CustomDateDeserializer.class)
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.START_TIME
     *
     * @param startTime the value for COURT_CASE_PLAN.START_TIME
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.REST_TIME
     *
     * @return the value of COURT_CASE_PLAN.REST_TIME
     *
     * @mbggenerated
     */
    @JsonSerialize(using = CustomDateSerializer.class)
	@JsonDeserialize(using = CustomDateDeserializer.class)
    public Date getRestTime() {
        return restTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.REST_TIME
     *
     * @param restTime the value for COURT_CASE_PLAN.REST_TIME
     *
     * @mbggenerated
     */
    public void setRestTime(Date restTime) {
        this.restTime = restTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.END_TIME
     *
     * @return the value of COURT_CASE_PLAN.END_TIME
     *
     * @mbggenerated
     */
    @JsonSerialize(using = CustomDateSerializer.class)
	@JsonDeserialize(using = CustomDateDeserializer.class)
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.END_TIME
     *
     * @param endTime the value for COURT_CASE_PLAN.END_TIME
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.ARCH_TIME
     *
     * @return the value of COURT_CASE_PLAN.ARCH_TIME
     *
     * @mbggenerated
     */
    public Date getArchTime() {
        return archTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.ARCH_TIME
     *
     * @param archTime the value for COURT_CASE_PLAN.ARCH_TIME
     *
     * @mbggenerated
     */
    public void setArchTime(Date archTime) {
        this.archTime = archTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.TRAIL_STATUS
     *
     * @return the value of COURT_CASE_PLAN.TRAIL_STATUS
     *
     * @mbggenerated
     */
    public String getTrailStatus() {
        return trailStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.TRAIL_STATUS
     *
     * @param trailStatus the value for COURT_CASE_PLAN.TRAIL_STATUS
     *
     * @mbggenerated
     */
    public void setTrailStatus(String trailStatus) {
        this.trailStatus = trailStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.ACCESS_URL
     *
     * @return the value of COURT_CASE_PLAN.ACCESS_URL
     *
     * @mbggenerated
     */
    public String getAccessUrl() {
        return accessUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.ACCESS_URL
     *
     * @param accessUrl the value for COURT_CASE_PLAN.ACCESS_URL
     *
     * @mbggenerated
     */
    public void setAccessUrl(String accessUrl) {
        this.accessUrl = accessUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.PUB_ACCESS_URL
     *
     * @return the value of COURT_CASE_PLAN.PUB_ACCESS_URL
     *
     * @mbggenerated
     */
    public String getPubAccessUrl() {
        return pubAccessUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.PUB_ACCESS_URL
     *
     * @param pubAccessUrl the value for COURT_CASE_PLAN.PUB_ACCESS_URL
     *
     * @mbggenerated
     */
    public void setPubAccessUrl(String pubAccessUrl) {
        this.pubAccessUrl = pubAccessUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.VOD_ACCESS_URL
     *
     * @return the value of COURT_CASE_PLAN.VOD_ACCESS_URL
     *
     * @mbggenerated
     */
    public String getVodAccessUrl() {
        return vodAccessUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.VOD_ACCESS_URL
     *
     * @param vodAccessUrl the value for COURT_CASE_PLAN.VOD_ACCESS_URL
     *
     * @mbggenerated
     */
    public void setVodAccessUrl(String vodAccessUrl) {
        this.vodAccessUrl = vodAccessUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.ALLOW_LIVE_FLAG
     *
     * @return the value of COURT_CASE_PLAN.ALLOW_LIVE_FLAG
     *
     * @mbggenerated
     */
    public Byte getAllowLiveFlag() {
        return allowLiveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.ALLOW_LIVE_FLAG
     *
     * @param allowLiveFlag the value for COURT_CASE_PLAN.ALLOW_LIVE_FLAG
     *
     * @mbggenerated
     */
    public void setAllowLiveFlag(Byte allowLiveFlag) {
        this.allowLiveFlag = allowLiveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.COURT_REC
     *
     * @return the value of COURT_CASE_PLAN.COURT_REC
     *
     * @mbggenerated
     */
    public String getCourtRec() {
        return courtRec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.COURT_REC
     *
     * @param courtRec the value for COURT_CASE_PLAN.COURT_REC
     *
     * @mbggenerated
     */
    public void setCourtRec(String courtRec) {
        this.courtRec = courtRec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.BURST_STATUS
     *
     * @return the value of COURT_CASE_PLAN.BURST_STATUS
     *
     * @mbggenerated
     */
    public Byte getBurstStatus() {
        return burstStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.BURST_STATUS
     *
     * @param burstStatus the value for COURT_CASE_PLAN.BURST_STATUS
     *
     * @mbggenerated
     */
    public void setBurstStatus(Byte burstStatus) {
        this.burstStatus = burstStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.COLLEGIAL_ID
     *
     * @return the value of COURT_CASE_PLAN.COLLEGIAL_ID
     *
     * @mbggenerated
     */
    public String getCollegialId() {
        return collegialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.COLLEGIAL_ID
     *
     * @param collegialId the value for COURT_CASE_PLAN.COLLEGIAL_ID
     *
     * @mbggenerated
     */
    public void setCollegialId(String collegialId) {
        this.collegialId = collegialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE_PLAN.TRIAL_LEVEL
     *
     * @return the value of COURT_CASE_PLAN.TRIAL_LEVEL
     *
     * @mbggenerated
     */
    public String getTrialLevel() {
        return trialLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE_PLAN.TRIAL_LEVEL
     *
     * @param trialLevel the value for COURT_CASE_PLAN.TRIAL_LEVEL
     *
     * @mbggenerated
     */
    public void setTrialLevel(String trialLevel) {
        this.trialLevel = trialLevel;
    }

	public CourtCaseWithBLOBs getCourtCase() {
		return courtCase;
	}

	public void setCourtCase(CourtCaseWithBLOBs courtCase) {
		this.courtCase = courtCase;
	}

	public List<CourtTrialRecording> getCourtTrialRecordings() {
		return courtTrialRecordings;
	}

	public void setCourtTrialRecordings(
			List<CourtTrialRecording> courtTrialRecordings) {
		this.courtTrialRecordings = courtTrialRecordings;
	}

	public String getCourtName() {
		return courtName;
	}

	public void setCourtName(String courtName) {
		this.courtName = courtName;
	}

	public String getCaseNum() {
		return caseNum;
	}

	public void setCaseNum(String caseNum) {
		this.caseNum = caseNum;
	}

	public String getCaseName() {
		return caseName;
	}

	public void setCaseName(String caseName) {
		this.caseName = caseName;
	}

	public String getCaseType() {
		return caseType;
	}

	public void setCaseType(String caseType) {
		this.caseType = caseType;
	}
    
}