package com.ht.court.model;

import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonDeserialize;
import org.codehaus.jackson.map.annotate.JsonSerialize;

import com.hx.HxModel;
import com.hx.common.CustomDateDeserializer;
import com.hx.common.CustomDateSerializer;

public class CourtCase extends HxModel {
	
	private static final long serialVersionUID = 4407275760350232897L;

//	private List<CourtCasePlan> plans;//排期数据集合
	
	private String courtName;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE.CASE_NUM
     *  案号
     * @mbggenerated
     */
    private String caseNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE.COURT_ID
     *  法院ID
     * @mbggenerated
     */
    private String courtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE.CASE_TYPE_ID
     *  案件类型
     * @mbggenerated
     */
    private String caseTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE.CASE_TYPE_NAME
     *   案件类型名称
     * @mbggenerated
     */
    private String caseTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE.CASE_NAME
     *   案件名称
     * @mbggenerated
     */
    private String caseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE.ACCUSER
     *  原告
     * @mbggenerated
     */
    private String accuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE.ACCUSER_LAWER
     *   原告律师
     * @mbggenerated
     */
    private String accuserLawer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE.ACCUSED
     *   被告
     * @mbggenerated
     */
    private String accused;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE.ACCUSED_LAWER
     *  被告律师
     * @mbggenerated
     */
    private String accusedLawer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE.REGISTER_TIME
     *   立案时间
     * @mbggenerated
     */
    private Date registerTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE.CASE_NUM
     *
     * @return the value of COURT_CASE.CASE_NUM
     *  
     * @mbggenerated
     */
    public String getCaseNum() {
        return caseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE.CASE_NUM
     *
     * @param caseNum the value for COURT_CASE.CASE_NUM
     *
     * @mbggenerated
     */
    public void setCaseNum(String caseNum) {
        this.caseNum = caseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE.COURT_ID
     *
     * @return the value of COURT_CASE.COURT_ID
     *
     * @mbggenerated
     */
    public String getCourtId() {
        return courtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE.COURT_ID
     *
     * @param courtId the value for COURT_CASE.COURT_ID
     *
     * @mbggenerated
     */
    public void setCourtId(String courtId) {
        this.courtId = courtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE.CASE_TYPE_ID
     *
     * @return the value of COURT_CASE.CASE_TYPE_ID
     *
     * @mbggenerated
     */
    public String getCaseTypeId() {
        return caseTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE.CASE_TYPE_ID
     *
     * @param caseTypeId the value for COURT_CASE.CASE_TYPE_ID
     *
     * @mbggenerated
     */
    public void setCaseTypeId(String caseTypeId) {
        this.caseTypeId = caseTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE.CASE_TYPE_NAME
     *
     * @return the value of COURT_CASE.CASE_TYPE_NAME
     *
     * @mbggenerated
     */
    public String getCaseTypeName() {
        return caseTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE.CASE_TYPE_NAME
     *
     * @param caseTypeName the value for COURT_CASE.CASE_TYPE_NAME
     *
     * @mbggenerated
     */
    public void setCaseTypeName(String caseTypeName) {
        this.caseTypeName = caseTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE.CASE_NAME
     *
     * @return the value of COURT_CASE.CASE_NAME
     *
     * @mbggenerated
     */
    public String getCaseName() {
        return caseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE.CASE_NAME
     *
     * @param caseName the value for COURT_CASE.CASE_NAME
     *
     * @mbggenerated
     */
    public void setCaseName(String caseName) {
        this.caseName = caseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE.ACCUSER
     *
     * @return the value of COURT_CASE.ACCUSER
     *
     * @mbggenerated
     */
    public String getAccuser() {
        return accuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE.ACCUSER
     *
     * @param accuser the value for COURT_CASE.ACCUSER
     *
     * @mbggenerated
     */
    public void setAccuser(String accuser) {
        this.accuser = accuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE.ACCUSER_LAWER
     *
     * @return the value of COURT_CASE.ACCUSER_LAWER
     *
     * @mbggenerated
     */
    public String getAccuserLawer() {
        return accuserLawer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE.ACCUSER_LAWER
     *
     * @param accuserLawer the value for COURT_CASE.ACCUSER_LAWER
     *
     * @mbggenerated
     */
    public void setAccuserLawer(String accuserLawer) {
        this.accuserLawer = accuserLawer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE.ACCUSED
     *
     * @return the value of COURT_CASE.ACCUSED
     *
     * @mbggenerated
     */
    public String getAccused() {
        return accused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE.ACCUSED
     *
     * @param accused the value for COURT_CASE.ACCUSED
     *
     * @mbggenerated
     */
    public void setAccused(String accused) {
        this.accused = accused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE.ACCUSED_LAWER
     *
     * @return the value of COURT_CASE.ACCUSED_LAWER
     *
     * @mbggenerated
     */
    public String getAccusedLawer() {
        return accusedLawer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE.ACCUSED_LAWER
     *
     * @param accusedLawer the value for COURT_CASE.ACCUSED_LAWER
     *
     * @mbggenerated
     */
    public void setAccusedLawer(String accusedLawer) {
        this.accusedLawer = accusedLawer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE.REGISTER_TIME
     *
     * @return the value of COURT_CASE.REGISTER_TIME
     *
     * @mbggenerated
     */
	@JsonSerialize(using = CustomDateSerializer.class)
	@JsonDeserialize(using = CustomDateDeserializer.class)
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE.REGISTER_TIME
     *
     * @param registerTime the value for COURT_CASE.REGISTER_TIME
     *
     * @mbggenerated
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

	public String getCourtName() {
		return courtName;
	}

	public void setCourtName(String courtName) {
		this.courtName = courtName;
	}
}