package com.ht.court.model;

import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonDeserialize;
import org.codehaus.jackson.map.annotate.JsonSerialize;

import com.hx.HxModel;
import com.hx.common.CustomDateDeserializer;
import com.hx.common.CustomDateSerializer;

public class CourtTrialRecording extends HxModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_TRIAL_RECORDING.PLAN_ID
     *
     * @mbggenerated
     */
    private String planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_TRIAL_RECORDING.CASE_ID
     *
     * @mbggenerated
     */
    private String caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_TRIAL_RECORDING.REMOTE_ID
     *
     * @mbggenerated
     */
    private String remoteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_TRIAL_RECORDING.CHANNEL_NUM
     *
     * @mbggenerated
     */
    private Integer channelNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_TRIAL_RECORDING.CHANNEL_NAME
     *
     * @mbggenerated
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_TRIAL_RECORDING.MEDIA_TYPE
     *
     * @mbggenerated
     */
    private String mediaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_TRIAL_RECORDING.RESOLUTION
     *
     * @mbggenerated
     */
    private String resolution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_TRIAL_RECORDING.START_TIME
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_TRIAL_RECORDING.END_TIME
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_TRIAL_RECORDING.CODE_RATE
     *
     * @mbggenerated
     */
    private Long codeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_TRIAL_RECORDING.FILE_NAME
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_TRIAL_RECORDING.FILE_SIZE
     *
     * @mbggenerated
     */
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_TRIAL_RECORDING.ACCESS_URL
     *
     * @mbggenerated
     */
    private String accessUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_TRIAL_RECORDING.REMOTE_FLAG
     *
     * @mbggenerated
     */
    private Byte remoteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_TRIAL_RECORDING.TOBECALLED_FLAG
     *
     * @mbggenerated
     */
    private Byte tobecalledFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_TRIAL_RECORDING.PIVOT
     *
     * @mbggenerated
     */
    private String pivot;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_TRIAL_RECORDING.PLAN_ID
     *
     * @return the value of COURT_TRIAL_RECORDING.PLAN_ID
     *
     * @mbggenerated
     */
    public String getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_TRIAL_RECORDING.PLAN_ID
     *
     * @param planId the value for COURT_TRIAL_RECORDING.PLAN_ID
     *
     * @mbggenerated
     */
    public void setPlanId(String planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_TRIAL_RECORDING.CASE_ID
     *
     * @return the value of COURT_TRIAL_RECORDING.CASE_ID
     *
     * @mbggenerated
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_TRIAL_RECORDING.CASE_ID
     *
     * @param caseId the value for COURT_TRIAL_RECORDING.CASE_ID
     *
     * @mbggenerated
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_TRIAL_RECORDING.REMOTE_ID
     *
     * @return the value of COURT_TRIAL_RECORDING.REMOTE_ID
     *
     * @mbggenerated
     */
    public String getRemoteId() {
        return remoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_TRIAL_RECORDING.REMOTE_ID
     *
     * @param remoteId the value for COURT_TRIAL_RECORDING.REMOTE_ID
     *
     * @mbggenerated
     */
    public void setRemoteId(String remoteId) {
        this.remoteId = remoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_TRIAL_RECORDING.CHANNEL_NUM
     *
     * @return the value of COURT_TRIAL_RECORDING.CHANNEL_NUM
     *
     * @mbggenerated
     */
    public Integer getChannelNum() {
        return channelNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_TRIAL_RECORDING.CHANNEL_NUM
     *
     * @param channelNum the value for COURT_TRIAL_RECORDING.CHANNEL_NUM
     *
     * @mbggenerated
     */
    public void setChannelNum(Integer channelNum) {
        this.channelNum = channelNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_TRIAL_RECORDING.CHANNEL_NAME
     *
     * @return the value of COURT_TRIAL_RECORDING.CHANNEL_NAME
     *
     * @mbggenerated
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_TRIAL_RECORDING.CHANNEL_NAME
     *
     * @param channelName the value for COURT_TRIAL_RECORDING.CHANNEL_NAME
     *
     * @mbggenerated
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_TRIAL_RECORDING.MEDIA_TYPE
     *
     * @return the value of COURT_TRIAL_RECORDING.MEDIA_TYPE
     *
     * @mbggenerated
     */
    public String getMediaType() {
        return mediaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_TRIAL_RECORDING.MEDIA_TYPE
     *
     * @param mediaType the value for COURT_TRIAL_RECORDING.MEDIA_TYPE
     *
     * @mbggenerated
     */
    public void setMediaType(String mediaType) {
        this.mediaType = mediaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_TRIAL_RECORDING.RESOLUTION
     *
     * @return the value of COURT_TRIAL_RECORDING.RESOLUTION
     *
     * @mbggenerated
     */
    public String getResolution() {
        return resolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_TRIAL_RECORDING.RESOLUTION
     *
     * @param resolution the value for COURT_TRIAL_RECORDING.RESOLUTION
     *
     * @mbggenerated
     */
    public void setResolution(String resolution) {
        this.resolution = resolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_TRIAL_RECORDING.START_TIME
     *
     * @return the value of COURT_TRIAL_RECORDING.START_TIME
     *
     * @mbggenerated
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    @JsonDeserialize(using = CustomDateDeserializer.class)
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_TRIAL_RECORDING.START_TIME
     *
     * @param startTime the value for COURT_TRIAL_RECORDING.START_TIME
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_TRIAL_RECORDING.END_TIME
     *
     * @return the value of COURT_TRIAL_RECORDING.END_TIME
     *
     * @mbggenerated
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    @JsonDeserialize(using = CustomDateDeserializer.class)
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_TRIAL_RECORDING.END_TIME
     *
     * @param endTime the value for COURT_TRIAL_RECORDING.END_TIME
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_TRIAL_RECORDING.CODE_RATE
     *
     * @return the value of COURT_TRIAL_RECORDING.CODE_RATE
     *
     * @mbggenerated
     */
    public Long getCodeRate() {
        return codeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_TRIAL_RECORDING.CODE_RATE
     *
     * @param codeRate the value for COURT_TRIAL_RECORDING.CODE_RATE
     *
     * @mbggenerated
     */
    public void setCodeRate(Long codeRate) {
        this.codeRate = codeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_TRIAL_RECORDING.FILE_NAME
     *
     * @return the value of COURT_TRIAL_RECORDING.FILE_NAME
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_TRIAL_RECORDING.FILE_NAME
     *
     * @param fileName the value for COURT_TRIAL_RECORDING.FILE_NAME
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_TRIAL_RECORDING.FILE_SIZE
     *
     * @return the value of COURT_TRIAL_RECORDING.FILE_SIZE
     *
     * @mbggenerated
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_TRIAL_RECORDING.FILE_SIZE
     *
     * @param fileSize the value for COURT_TRIAL_RECORDING.FILE_SIZE
     *
     * @mbggenerated
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_TRIAL_RECORDING.ACCESS_URL
     *
     * @return the value of COURT_TRIAL_RECORDING.ACCESS_URL
     *
     * @mbggenerated
     */
    public String getAccessUrl() {
        return accessUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_TRIAL_RECORDING.ACCESS_URL
     *
     * @param accessUrl the value for COURT_TRIAL_RECORDING.ACCESS_URL
     *
     * @mbggenerated
     */
    public void setAccessUrl(String accessUrl) {
        this.accessUrl = accessUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_TRIAL_RECORDING.REMOTE_FLAG
     *
     * @return the value of COURT_TRIAL_RECORDING.REMOTE_FLAG
     *
     * @mbggenerated
     */
    public Byte getRemoteFlag() {
        return remoteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_TRIAL_RECORDING.REMOTE_FLAG
     *
     * @param remoteFlag the value for COURT_TRIAL_RECORDING.REMOTE_FLAG
     *
     * @mbggenerated
     */
    public void setRemoteFlag(Byte remoteFlag) {
        this.remoteFlag = remoteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_TRIAL_RECORDING.TOBECALLED_FLAG
     *
     * @return the value of COURT_TRIAL_RECORDING.TOBECALLED_FLAG
     *
     * @mbggenerated
     */
    public Byte getTobecalledFlag() {
        return tobecalledFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_TRIAL_RECORDING.TOBECALLED_FLAG
     *
     * @param tobecalledFlag the value for COURT_TRIAL_RECORDING.TOBECALLED_FLAG
     *
     * @mbggenerated
     */
    public void setTobecalledFlag(Byte tobecalledFlag) {
        this.tobecalledFlag = tobecalledFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_TRIAL_RECORDING.PIVOT
     *
     * @return the value of COURT_TRIAL_RECORDING.PIVOT
     *
     * @mbggenerated
     */
    public String getPivot() {
        return pivot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_TRIAL_RECORDING.PIVOT
     *
     * @param pivot the value for COURT_TRIAL_RECORDING.PIVOT
     *
     * @mbggenerated
     */
    public void setPivot(String pivot) {
        this.pivot = pivot;
    }
}