package com.ht.court.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CourtCasePlanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    public CourtCasePlanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCaseIdIsNull() {
            addCriterion("CASE_ID is null");
            return (Criteria) this;
        }

        public Criteria andCaseIdIsNotNull() {
            addCriterion("CASE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCaseIdEqualTo(String value) {
            addCriterion("CASE_ID =", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotEqualTo(String value) {
            addCriterion("CASE_ID <>", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdGreaterThan(String value) {
            addCriterion("CASE_ID >", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdGreaterThanOrEqualTo(String value) {
            addCriterion("CASE_ID >=", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdLessThan(String value) {
            addCriterion("CASE_ID <", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdLessThanOrEqualTo(String value) {
            addCriterion("CASE_ID <=", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdLike(String value) {
            addCriterion("CASE_ID like", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotLike(String value) {
            addCriterion("CASE_ID not like", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdIn(List<String> values) {
            addCriterion("CASE_ID in", values, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotIn(List<String> values) {
            addCriterion("CASE_ID not in", values, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdBetween(String value1, String value2) {
            addCriterion("CASE_ID between", value1, value2, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotBetween(String value1, String value2) {
            addCriterion("CASE_ID not between", value1, value2, "caseId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdIsNull() {
            addCriterion("JUDGE_ID is null");
            return (Criteria) this;
        }

        public Criteria andJudgeIdIsNotNull() {
            addCriterion("JUDGE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andJudgeIdEqualTo(String value) {
            addCriterion("JUDGE_ID =", value, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdNotEqualTo(String value) {
            addCriterion("JUDGE_ID <>", value, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdGreaterThan(String value) {
            addCriterion("JUDGE_ID >", value, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdGreaterThanOrEqualTo(String value) {
            addCriterion("JUDGE_ID >=", value, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdLessThan(String value) {
            addCriterion("JUDGE_ID <", value, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdLessThanOrEqualTo(String value) {
            addCriterion("JUDGE_ID <=", value, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdLike(String value) {
            addCriterion("JUDGE_ID like", value, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdNotLike(String value) {
            addCriterion("JUDGE_ID not like", value, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdIn(List<String> values) {
            addCriterion("JUDGE_ID in", values, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdNotIn(List<String> values) {
            addCriterion("JUDGE_ID not in", values, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdBetween(String value1, String value2) {
            addCriterion("JUDGE_ID between", value1, value2, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdNotBetween(String value1, String value2) {
            addCriterion("JUDGE_ID not between", value1, value2, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeNameIsNull() {
            addCriterion("JUDGE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andJudgeNameIsNotNull() {
            addCriterion("JUDGE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andJudgeNameEqualTo(String value) {
            addCriterion("JUDGE_NAME =", value, "judgeName");
            return (Criteria) this;
        }

        public Criteria andJudgeNameNotEqualTo(String value) {
            addCriterion("JUDGE_NAME <>", value, "judgeName");
            return (Criteria) this;
        }

        public Criteria andJudgeNameGreaterThan(String value) {
            addCriterion("JUDGE_NAME >", value, "judgeName");
            return (Criteria) this;
        }

        public Criteria andJudgeNameGreaterThanOrEqualTo(String value) {
            addCriterion("JUDGE_NAME >=", value, "judgeName");
            return (Criteria) this;
        }

        public Criteria andJudgeNameLessThan(String value) {
            addCriterion("JUDGE_NAME <", value, "judgeName");
            return (Criteria) this;
        }

        public Criteria andJudgeNameLessThanOrEqualTo(String value) {
            addCriterion("JUDGE_NAME <=", value, "judgeName");
            return (Criteria) this;
        }

        public Criteria andJudgeNameLike(String value) {
            addCriterion("JUDGE_NAME like", value, "judgeName");
            return (Criteria) this;
        }

        public Criteria andJudgeNameNotLike(String value) {
            addCriterion("JUDGE_NAME not like", value, "judgeName");
            return (Criteria) this;
        }

        public Criteria andJudgeNameIn(List<String> values) {
            addCriterion("JUDGE_NAME in", values, "judgeName");
            return (Criteria) this;
        }

        public Criteria andJudgeNameNotIn(List<String> values) {
            addCriterion("JUDGE_NAME not in", values, "judgeName");
            return (Criteria) this;
        }

        public Criteria andJudgeNameBetween(String value1, String value2) {
            addCriterion("JUDGE_NAME between", value1, value2, "judgeName");
            return (Criteria) this;
        }

        public Criteria andJudgeNameNotBetween(String value1, String value2) {
            addCriterion("JUDGE_NAME not between", value1, value2, "judgeName");
            return (Criteria) this;
        }

        public Criteria andClerkIdIsNull() {
            addCriterion("CLERK_ID is null");
            return (Criteria) this;
        }

        public Criteria andClerkIdIsNotNull() {
            addCriterion("CLERK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andClerkIdEqualTo(String value) {
            addCriterion("CLERK_ID =", value, "clerkId");
            return (Criteria) this;
        }

        public Criteria andClerkIdNotEqualTo(String value) {
            addCriterion("CLERK_ID <>", value, "clerkId");
            return (Criteria) this;
        }

        public Criteria andClerkIdGreaterThan(String value) {
            addCriterion("CLERK_ID >", value, "clerkId");
            return (Criteria) this;
        }

        public Criteria andClerkIdGreaterThanOrEqualTo(String value) {
            addCriterion("CLERK_ID >=", value, "clerkId");
            return (Criteria) this;
        }

        public Criteria andClerkIdLessThan(String value) {
            addCriterion("CLERK_ID <", value, "clerkId");
            return (Criteria) this;
        }

        public Criteria andClerkIdLessThanOrEqualTo(String value) {
            addCriterion("CLERK_ID <=", value, "clerkId");
            return (Criteria) this;
        }

        public Criteria andClerkIdLike(String value) {
            addCriterion("CLERK_ID like", value, "clerkId");
            return (Criteria) this;
        }

        public Criteria andClerkIdNotLike(String value) {
            addCriterion("CLERK_ID not like", value, "clerkId");
            return (Criteria) this;
        }

        public Criteria andClerkIdIn(List<String> values) {
            addCriterion("CLERK_ID in", values, "clerkId");
            return (Criteria) this;
        }

        public Criteria andClerkIdNotIn(List<String> values) {
            addCriterion("CLERK_ID not in", values, "clerkId");
            return (Criteria) this;
        }

        public Criteria andClerkIdBetween(String value1, String value2) {
            addCriterion("CLERK_ID between", value1, value2, "clerkId");
            return (Criteria) this;
        }

        public Criteria andClerkIdNotBetween(String value1, String value2) {
            addCriterion("CLERK_ID not between", value1, value2, "clerkId");
            return (Criteria) this;
        }

        public Criteria andClerkNameIsNull() {
            addCriterion("CLERK_NAME is null");
            return (Criteria) this;
        }

        public Criteria andClerkNameIsNotNull() {
            addCriterion("CLERK_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andClerkNameEqualTo(String value) {
            addCriterion("CLERK_NAME =", value, "clerkName");
            return (Criteria) this;
        }

        public Criteria andClerkNameNotEqualTo(String value) {
            addCriterion("CLERK_NAME <>", value, "clerkName");
            return (Criteria) this;
        }

        public Criteria andClerkNameGreaterThan(String value) {
            addCriterion("CLERK_NAME >", value, "clerkName");
            return (Criteria) this;
        }

        public Criteria andClerkNameGreaterThanOrEqualTo(String value) {
            addCriterion("CLERK_NAME >=", value, "clerkName");
            return (Criteria) this;
        }

        public Criteria andClerkNameLessThan(String value) {
            addCriterion("CLERK_NAME <", value, "clerkName");
            return (Criteria) this;
        }

        public Criteria andClerkNameLessThanOrEqualTo(String value) {
            addCriterion("CLERK_NAME <=", value, "clerkName");
            return (Criteria) this;
        }

        public Criteria andClerkNameLike(String value) {
            addCriterion("CLERK_NAME like", value, "clerkName");
            return (Criteria) this;
        }

        public Criteria andClerkNameNotLike(String value) {
            addCriterion("CLERK_NAME not like", value, "clerkName");
            return (Criteria) this;
        }

        public Criteria andClerkNameIn(List<String> values) {
            addCriterion("CLERK_NAME in", values, "clerkName");
            return (Criteria) this;
        }

        public Criteria andClerkNameNotIn(List<String> values) {
            addCriterion("CLERK_NAME not in", values, "clerkName");
            return (Criteria) this;
        }

        public Criteria andClerkNameBetween(String value1, String value2) {
            addCriterion("CLERK_NAME between", value1, value2, "clerkName");
            return (Criteria) this;
        }

        public Criteria andClerkNameNotBetween(String value1, String value2) {
            addCriterion("CLERK_NAME not between", value1, value2, "clerkName");
            return (Criteria) this;
        }

        public Criteria andCourtIdIsNull() {
            addCriterion("COURT_ID is null");
            return (Criteria) this;
        }

        public Criteria andCourtIdIsNotNull() {
            addCriterion("COURT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCourtIdEqualTo(String value) {
            addCriterion("COURT_ID =", value, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdNotEqualTo(String value) {
            addCriterion("COURT_ID <>", value, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdGreaterThan(String value) {
            addCriterion("COURT_ID >", value, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdGreaterThanOrEqualTo(String value) {
            addCriterion("COURT_ID >=", value, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdLessThan(String value) {
            addCriterion("COURT_ID <", value, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdLessThanOrEqualTo(String value) {
            addCriterion("COURT_ID <=", value, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdLike(String value) {
            addCriterion("COURT_ID like", value, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdNotLike(String value) {
            addCriterion("COURT_ID not like", value, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdIn(List<String> values) {
            addCriterion("COURT_ID in", values, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdNotIn(List<String> values) {
            addCriterion("COURT_ID not in", values, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdBetween(String value1, String value2) {
            addCriterion("COURT_ID between", value1, value2, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdNotBetween(String value1, String value2) {
            addCriterion("COURT_ID not between", value1, value2, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdIsNull() {
            addCriterion("COURT_ROOM_ID is null");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdIsNotNull() {
            addCriterion("COURT_ROOM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdEqualTo(String value) {
            addCriterion("COURT_ROOM_ID =", value, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdNotEqualTo(String value) {
            addCriterion("COURT_ROOM_ID <>", value, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdGreaterThan(String value) {
            addCriterion("COURT_ROOM_ID >", value, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdGreaterThanOrEqualTo(String value) {
            addCriterion("COURT_ROOM_ID >=", value, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdLessThan(String value) {
            addCriterion("COURT_ROOM_ID <", value, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdLessThanOrEqualTo(String value) {
            addCriterion("COURT_ROOM_ID <=", value, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdLike(String value) {
            addCriterion("COURT_ROOM_ID like", value, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdNotLike(String value) {
            addCriterion("COURT_ROOM_ID not like", value, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdIn(List<String> values) {
            addCriterion("COURT_ROOM_ID in", values, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdNotIn(List<String> values) {
            addCriterion("COURT_ROOM_ID not in", values, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdBetween(String value1, String value2) {
            addCriterion("COURT_ROOM_ID between", value1, value2, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdNotBetween(String value1, String value2) {
            addCriterion("COURT_ROOM_ID not between", value1, value2, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameIsNull() {
            addCriterion("COURT_ROOM_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameIsNotNull() {
            addCriterion("COURT_ROOM_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameEqualTo(String value) {
            addCriterion("COURT_ROOM_NAME =", value, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameNotEqualTo(String value) {
            addCriterion("COURT_ROOM_NAME <>", value, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameGreaterThan(String value) {
            addCriterion("COURT_ROOM_NAME >", value, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameGreaterThanOrEqualTo(String value) {
            addCriterion("COURT_ROOM_NAME >=", value, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameLessThan(String value) {
            addCriterion("COURT_ROOM_NAME <", value, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameLessThanOrEqualTo(String value) {
            addCriterion("COURT_ROOM_NAME <=", value, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameLike(String value) {
            addCriterion("COURT_ROOM_NAME like", value, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameNotLike(String value) {
            addCriterion("COURT_ROOM_NAME not like", value, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameIn(List<String> values) {
            addCriterion("COURT_ROOM_NAME in", values, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameNotIn(List<String> values) {
            addCriterion("COURT_ROOM_NAME not in", values, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameBetween(String value1, String value2) {
            addCriterion("COURT_ROOM_NAME between", value1, value2, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameNotBetween(String value1, String value2) {
            addCriterion("COURT_ROOM_NAME not between", value1, value2, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeIsNull() {
            addCriterion("PLAN_START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeIsNotNull() {
            addCriterion("PLAN_START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeEqualTo(Date value) {
            addCriterion("PLAN_START_TIME =", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeNotEqualTo(Date value) {
            addCriterion("PLAN_START_TIME <>", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeGreaterThan(Date value) {
            addCriterion("PLAN_START_TIME >", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("PLAN_START_TIME >=", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeLessThan(Date value) {
            addCriterion("PLAN_START_TIME <", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("PLAN_START_TIME <=", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeIn(List<Date> values) {
            addCriterion("PLAN_START_TIME in", values, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeNotIn(List<Date> values) {
            addCriterion("PLAN_START_TIME not in", values, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeBetween(Date value1, Date value2) {
            addCriterion("PLAN_START_TIME between", value1, value2, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("PLAN_START_TIME not between", value1, value2, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeIsNull() {
            addCriterion("PLAN_END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeIsNotNull() {
            addCriterion("PLAN_END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeEqualTo(Date value) {
            addCriterion("PLAN_END_TIME =", value, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeNotEqualTo(Date value) {
            addCriterion("PLAN_END_TIME <>", value, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeGreaterThan(Date value) {
            addCriterion("PLAN_END_TIME >", value, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("PLAN_END_TIME >=", value, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeLessThan(Date value) {
            addCriterion("PLAN_END_TIME <", value, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("PLAN_END_TIME <=", value, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeIn(List<Date> values) {
            addCriterion("PLAN_END_TIME in", values, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeNotIn(List<Date> values) {
            addCriterion("PLAN_END_TIME not in", values, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeBetween(Date value1, Date value2) {
            addCriterion("PLAN_END_TIME between", value1, value2, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("PLAN_END_TIME not between", value1, value2, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("START_TIME =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("START_TIME <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("START_TIME >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("START_TIME >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("START_TIME <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("START_TIME <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("START_TIME in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("START_TIME not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("START_TIME between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("START_TIME not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andRestTimeIsNull() {
            addCriterion("REST_TIME is null");
            return (Criteria) this;
        }

        public Criteria andRestTimeIsNotNull() {
            addCriterion("REST_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andRestTimeEqualTo(Date value) {
            addCriterion("REST_TIME =", value, "restTime");
            return (Criteria) this;
        }

        public Criteria andRestTimeNotEqualTo(Date value) {
            addCriterion("REST_TIME <>", value, "restTime");
            return (Criteria) this;
        }

        public Criteria andRestTimeGreaterThan(Date value) {
            addCriterion("REST_TIME >", value, "restTime");
            return (Criteria) this;
        }

        public Criteria andRestTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REST_TIME >=", value, "restTime");
            return (Criteria) this;
        }

        public Criteria andRestTimeLessThan(Date value) {
            addCriterion("REST_TIME <", value, "restTime");
            return (Criteria) this;
        }

        public Criteria andRestTimeLessThanOrEqualTo(Date value) {
            addCriterion("REST_TIME <=", value, "restTime");
            return (Criteria) this;
        }

        public Criteria andRestTimeIn(List<Date> values) {
            addCriterion("REST_TIME in", values, "restTime");
            return (Criteria) this;
        }

        public Criteria andRestTimeNotIn(List<Date> values) {
            addCriterion("REST_TIME not in", values, "restTime");
            return (Criteria) this;
        }

        public Criteria andRestTimeBetween(Date value1, Date value2) {
            addCriterion("REST_TIME between", value1, value2, "restTime");
            return (Criteria) this;
        }

        public Criteria andRestTimeNotBetween(Date value1, Date value2) {
            addCriterion("REST_TIME not between", value1, value2, "restTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("END_TIME =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("END_TIME <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("END_TIME >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("END_TIME >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("END_TIME <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("END_TIME <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("END_TIME in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("END_TIME not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("END_TIME between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("END_TIME not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andArchTimeIsNull() {
            addCriterion("ARCH_TIME is null");
            return (Criteria) this;
        }

        public Criteria andArchTimeIsNotNull() {
            addCriterion("ARCH_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andArchTimeEqualTo(Date value) {
            addCriterion("ARCH_TIME =", value, "archTime");
            return (Criteria) this;
        }

        public Criteria andArchTimeNotEqualTo(Date value) {
            addCriterion("ARCH_TIME <>", value, "archTime");
            return (Criteria) this;
        }

        public Criteria andArchTimeGreaterThan(Date value) {
            addCriterion("ARCH_TIME >", value, "archTime");
            return (Criteria) this;
        }

        public Criteria andArchTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ARCH_TIME >=", value, "archTime");
            return (Criteria) this;
        }

        public Criteria andArchTimeLessThan(Date value) {
            addCriterion("ARCH_TIME <", value, "archTime");
            return (Criteria) this;
        }

        public Criteria andArchTimeLessThanOrEqualTo(Date value) {
            addCriterion("ARCH_TIME <=", value, "archTime");
            return (Criteria) this;
        }

        public Criteria andArchTimeIn(List<Date> values) {
            addCriterion("ARCH_TIME in", values, "archTime");
            return (Criteria) this;
        }

        public Criteria andArchTimeNotIn(List<Date> values) {
            addCriterion("ARCH_TIME not in", values, "archTime");
            return (Criteria) this;
        }

        public Criteria andArchTimeBetween(Date value1, Date value2) {
            addCriterion("ARCH_TIME between", value1, value2, "archTime");
            return (Criteria) this;
        }

        public Criteria andArchTimeNotBetween(Date value1, Date value2) {
            addCriterion("ARCH_TIME not between", value1, value2, "archTime");
            return (Criteria) this;
        }

        public Criteria andTrailStatusIsNull() {
            addCriterion("TRAIL_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andTrailStatusIsNotNull() {
            addCriterion("TRAIL_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andTrailStatusEqualTo(String value) {
            addCriterion("TRAIL_STATUS =", value, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andTrailStatusNotEqualTo(String value) {
            addCriterion("TRAIL_STATUS <>", value, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andTrailStatusGreaterThan(String value) {
            addCriterion("TRAIL_STATUS >", value, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andTrailStatusGreaterThanOrEqualTo(String value) {
            addCriterion("TRAIL_STATUS >=", value, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andTrailStatusLessThan(String value) {
            addCriterion("TRAIL_STATUS <", value, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andTrailStatusLessThanOrEqualTo(String value) {
            addCriterion("TRAIL_STATUS <=", value, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andTrailStatusLike(String value) {
            addCriterion("TRAIL_STATUS like", value, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andTrailStatusNotLike(String value) {
            addCriterion("TRAIL_STATUS not like", value, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andTrailStatusIn(List<String> values) {
            addCriterion("TRAIL_STATUS in", values, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andTrailStatusNotIn(List<String> values) {
            addCriterion("TRAIL_STATUS not in", values, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andTrailStatusBetween(String value1, String value2) {
            addCriterion("TRAIL_STATUS between", value1, value2, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andTrailStatusNotBetween(String value1, String value2) {
            addCriterion("TRAIL_STATUS not between", value1, value2, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andAllowLiveFlagIsNull() {
            addCriterion("ALLOW_LIVE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andAllowLiveFlagIsNotNull() {
            addCriterion("ALLOW_LIVE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andAllowLiveFlagEqualTo(Byte value) {
            addCriterion("ALLOW_LIVE_FLAG =", value, "allowLiveFlag");
            return (Criteria) this;
        }

        public Criteria andAllowLiveFlagNotEqualTo(Byte value) {
            addCriterion("ALLOW_LIVE_FLAG <>", value, "allowLiveFlag");
            return (Criteria) this;
        }

        public Criteria andAllowLiveFlagGreaterThan(Byte value) {
            addCriterion("ALLOW_LIVE_FLAG >", value, "allowLiveFlag");
            return (Criteria) this;
        }

        public Criteria andAllowLiveFlagGreaterThanOrEqualTo(Byte value) {
            addCriterion("ALLOW_LIVE_FLAG >=", value, "allowLiveFlag");
            return (Criteria) this;
        }

        public Criteria andAllowLiveFlagLessThan(Byte value) {
            addCriterion("ALLOW_LIVE_FLAG <", value, "allowLiveFlag");
            return (Criteria) this;
        }

        public Criteria andAllowLiveFlagLessThanOrEqualTo(Byte value) {
            addCriterion("ALLOW_LIVE_FLAG <=", value, "allowLiveFlag");
            return (Criteria) this;
        }

        public Criteria andAllowLiveFlagIn(List<Byte> values) {
            addCriterion("ALLOW_LIVE_FLAG in", values, "allowLiveFlag");
            return (Criteria) this;
        }

        public Criteria andAllowLiveFlagNotIn(List<Byte> values) {
            addCriterion("ALLOW_LIVE_FLAG not in", values, "allowLiveFlag");
            return (Criteria) this;
        }

        public Criteria andAllowLiveFlagBetween(Byte value1, Byte value2) {
            addCriterion("ALLOW_LIVE_FLAG between", value1, value2, "allowLiveFlag");
            return (Criteria) this;
        }

        public Criteria andAllowLiveFlagNotBetween(Byte value1, Byte value2) {
            addCriterion("ALLOW_LIVE_FLAG not between", value1, value2, "allowLiveFlag");
            return (Criteria) this;
        }

        public Criteria andCourtRecIsNull() {
            addCriterion("COURT_REC is null");
            return (Criteria) this;
        }

        public Criteria andCourtRecIsNotNull() {
            addCriterion("COURT_REC is not null");
            return (Criteria) this;
        }

        public Criteria andCourtRecEqualTo(String value) {
            addCriterion("COURT_REC =", value, "courtRec");
            return (Criteria) this;
        }

        public Criteria andCourtRecNotEqualTo(String value) {
            addCriterion("COURT_REC <>", value, "courtRec");
            return (Criteria) this;
        }

        public Criteria andCourtRecGreaterThan(String value) {
            addCriterion("COURT_REC >", value, "courtRec");
            return (Criteria) this;
        }

        public Criteria andCourtRecGreaterThanOrEqualTo(String value) {
            addCriterion("COURT_REC >=", value, "courtRec");
            return (Criteria) this;
        }

        public Criteria andCourtRecLessThan(String value) {
            addCriterion("COURT_REC <", value, "courtRec");
            return (Criteria) this;
        }

        public Criteria andCourtRecLessThanOrEqualTo(String value) {
            addCriterion("COURT_REC <=", value, "courtRec");
            return (Criteria) this;
        }

        public Criteria andCourtRecLike(String value) {
            addCriterion("COURT_REC like", value, "courtRec");
            return (Criteria) this;
        }

        public Criteria andCourtRecNotLike(String value) {
            addCriterion("COURT_REC not like", value, "courtRec");
            return (Criteria) this;
        }

        public Criteria andCourtRecIn(List<String> values) {
            addCriterion("COURT_REC in", values, "courtRec");
            return (Criteria) this;
        }

        public Criteria andCourtRecNotIn(List<String> values) {
            addCriterion("COURT_REC not in", values, "courtRec");
            return (Criteria) this;
        }

        public Criteria andCourtRecBetween(String value1, String value2) {
            addCriterion("COURT_REC between", value1, value2, "courtRec");
            return (Criteria) this;
        }

        public Criteria andCourtRecNotBetween(String value1, String value2) {
            addCriterion("COURT_REC not between", value1, value2, "courtRec");
            return (Criteria) this;
        }

        public Criteria andBurstStatusIsNull() {
            addCriterion("BURST_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andBurstStatusIsNotNull() {
            addCriterion("BURST_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andBurstStatusEqualTo(Byte value) {
            addCriterion("BURST_STATUS =", value, "burstStatus");
            return (Criteria) this;
        }

        public Criteria andBurstStatusNotEqualTo(Byte value) {
            addCriterion("BURST_STATUS <>", value, "burstStatus");
            return (Criteria) this;
        }

        public Criteria andBurstStatusGreaterThan(Byte value) {
            addCriterion("BURST_STATUS >", value, "burstStatus");
            return (Criteria) this;
        }

        public Criteria andBurstStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("BURST_STATUS >=", value, "burstStatus");
            return (Criteria) this;
        }

        public Criteria andBurstStatusLessThan(Byte value) {
            addCriterion("BURST_STATUS <", value, "burstStatus");
            return (Criteria) this;
        }

        public Criteria andBurstStatusLessThanOrEqualTo(Byte value) {
            addCriterion("BURST_STATUS <=", value, "burstStatus");
            return (Criteria) this;
        }

        public Criteria andBurstStatusIn(List<Byte> values) {
            addCriterion("BURST_STATUS in", values, "burstStatus");
            return (Criteria) this;
        }

        public Criteria andBurstStatusNotIn(List<Byte> values) {
            addCriterion("BURST_STATUS not in", values, "burstStatus");
            return (Criteria) this;
        }

        public Criteria andBurstStatusBetween(Byte value1, Byte value2) {
            addCriterion("BURST_STATUS between", value1, value2, "burstStatus");
            return (Criteria) this;
        }

        public Criteria andBurstStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("BURST_STATUS not between", value1, value2, "burstStatus");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("DEL_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("DEL_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Boolean value) {
            addCriterion("DEL_FLAG =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Boolean value) {
            addCriterion("DEL_FLAG <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Boolean value) {
            addCriterion("DEL_FLAG >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("DEL_FLAG >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Boolean value) {
            addCriterion("DEL_FLAG <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("DEL_FLAG <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Boolean> values) {
            addCriterion("DEL_FLAG in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Boolean> values) {
            addCriterion("DEL_FLAG not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("DEL_FLAG between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("DEL_FLAG not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("CREATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("CREATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("CREATE_USER_ID =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("CREATE_USER_ID <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("CREATE_USER_ID >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_ID >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("CREATE_USER_ID <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_ID <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("CREATE_USER_ID like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("CREATE_USER_ID not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("CREATE_USER_ID in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("CREATE_USER_ID not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("CREATE_USER_ID between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER_ID not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("UPDATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("UPDATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("UPDATE_USER =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("UPDATE_USER <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("UPDATE_USER >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("UPDATE_USER <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("UPDATE_USER like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("UPDATE_USER not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("UPDATE_USER in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("UPDATE_USER not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("UPDATE_USER between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("UPDATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("UPDATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("UPDATE_USER_ID =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("UPDATE_USER_ID >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("UPDATE_USER_ID <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("UPDATE_USER_ID like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("UPDATE_USER_ID not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("UPDATE_USER_ID in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("UPDATE_USER_ID not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdIsNull() {
            addCriterion("ROOT_ORG_ID is null");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdIsNotNull() {
            addCriterion("ROOT_ORG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdEqualTo(String value) {
            addCriterion("ROOT_ORG_ID =", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdNotEqualTo(String value) {
            addCriterion("ROOT_ORG_ID <>", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdGreaterThan(String value) {
            addCriterion("ROOT_ORG_ID >", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdGreaterThanOrEqualTo(String value) {
            addCriterion("ROOT_ORG_ID >=", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdLessThan(String value) {
            addCriterion("ROOT_ORG_ID <", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdLessThanOrEqualTo(String value) {
            addCriterion("ROOT_ORG_ID <=", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdLike(String value) {
            addCriterion("ROOT_ORG_ID like", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdNotLike(String value) {
            addCriterion("ROOT_ORG_ID not like", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdIn(List<String> values) {
            addCriterion("ROOT_ORG_ID in", values, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdNotIn(List<String> values) {
            addCriterion("ROOT_ORG_ID not in", values, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdBetween(String value1, String value2) {
            addCriterion("ROOT_ORG_ID between", value1, value2, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdNotBetween(String value1, String value2) {
            addCriterion("ROOT_ORG_ID not between", value1, value2, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNull() {
            addCriterion("ORG_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNotNull() {
            addCriterion("ORG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrgIdEqualTo(String value) {
            addCriterion("ORG_ID =", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotEqualTo(String value) {
            addCriterion("ORG_ID <>", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThan(String value) {
            addCriterion("ORG_ID >", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_ID >=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThan(String value) {
            addCriterion("ORG_ID <", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThanOrEqualTo(String value) {
            addCriterion("ORG_ID <=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLike(String value) {
            addCriterion("ORG_ID like", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotLike(String value) {
            addCriterion("ORG_ID not like", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdIn(List<String> values) {
            addCriterion("ORG_ID in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotIn(List<String> values) {
            addCriterion("ORG_ID not in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdBetween(String value1, String value2) {
            addCriterion("ORG_ID between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotBetween(String value1, String value2) {
            addCriterion("ORG_ID not between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andAccessUrlIsNull() {
            addCriterion("ACCESS_URL is null");
            return (Criteria) this;
        }

        public Criteria andAccessUrlIsNotNull() {
            addCriterion("ACCESS_URL is not null");
            return (Criteria) this;
        }

        public Criteria andAccessUrlEqualTo(String value) {
            addCriterion("ACCESS_URL =", value, "accessUrl");
            return (Criteria) this;
        }

        public Criteria andAccessUrlNotEqualTo(String value) {
            addCriterion("ACCESS_URL <>", value, "accessUrl");
            return (Criteria) this;
        }

        public Criteria andAccessUrlGreaterThan(String value) {
            addCriterion("ACCESS_URL >", value, "accessUrl");
            return (Criteria) this;
        }

        public Criteria andAccessUrlGreaterThanOrEqualTo(String value) {
            addCriterion("ACCESS_URL >=", value, "accessUrl");
            return (Criteria) this;
        }

        public Criteria andAccessUrlLessThan(String value) {
            addCriterion("ACCESS_URL <", value, "accessUrl");
            return (Criteria) this;
        }

        public Criteria andAccessUrlLessThanOrEqualTo(String value) {
            addCriterion("ACCESS_URL <=", value, "accessUrl");
            return (Criteria) this;
        }

        public Criteria andAccessUrlLike(String value) {
            addCriterion("ACCESS_URL like", value, "accessUrl");
            return (Criteria) this;
        }

        public Criteria andAccessUrlNotLike(String value) {
            addCriterion("ACCESS_URL not like", value, "accessUrl");
            return (Criteria) this;
        }

        public Criteria andAccessUrlIn(List<String> values) {
            addCriterion("ACCESS_URL in", values, "accessUrl");
            return (Criteria) this;
        }

        public Criteria andAccessUrlNotIn(List<String> values) {
            addCriterion("ACCESS_URL not in", values, "accessUrl");
            return (Criteria) this;
        }

        public Criteria andAccessUrlBetween(String value1, String value2) {
            addCriterion("ACCESS_URL between", value1, value2, "accessUrl");
            return (Criteria) this;
        }

        public Criteria andAccessUrlNotBetween(String value1, String value2) {
            addCriterion("ACCESS_URL not between", value1, value2, "accessUrl");
            return (Criteria) this;
        }

        public Criteria andPubAccessUrlIsNull() {
            addCriterion("PUB_ACCESS_URL is null");
            return (Criteria) this;
        }

        public Criteria andPubAccessUrlIsNotNull() {
            addCriterion("PUB_ACCESS_URL is not null");
            return (Criteria) this;
        }

        public Criteria andPubAccessUrlEqualTo(String value) {
            addCriterion("PUB_ACCESS_URL =", value, "pubAccessUrl");
            return (Criteria) this;
        }

        public Criteria andPubAccessUrlNotEqualTo(String value) {
            addCriterion("PUB_ACCESS_URL <>", value, "pubAccessUrl");
            return (Criteria) this;
        }

        public Criteria andPubAccessUrlGreaterThan(String value) {
            addCriterion("PUB_ACCESS_URL >", value, "pubAccessUrl");
            return (Criteria) this;
        }

        public Criteria andPubAccessUrlGreaterThanOrEqualTo(String value) {
            addCriterion("PUB_ACCESS_URL >=", value, "pubAccessUrl");
            return (Criteria) this;
        }

        public Criteria andPubAccessUrlLessThan(String value) {
            addCriterion("PUB_ACCESS_URL <", value, "pubAccessUrl");
            return (Criteria) this;
        }

        public Criteria andPubAccessUrlLessThanOrEqualTo(String value) {
            addCriterion("PUB_ACCESS_URL <=", value, "pubAccessUrl");
            return (Criteria) this;
        }

        public Criteria andPubAccessUrlLike(String value) {
            addCriterion("PUB_ACCESS_URL like", value, "pubAccessUrl");
            return (Criteria) this;
        }

        public Criteria andPubAccessUrlNotLike(String value) {
            addCriterion("PUB_ACCESS_URL not like", value, "pubAccessUrl");
            return (Criteria) this;
        }

        public Criteria andPubAccessUrlIn(List<String> values) {
            addCriterion("PUB_ACCESS_URL in", values, "pubAccessUrl");
            return (Criteria) this;
        }

        public Criteria andPubAccessUrlNotIn(List<String> values) {
            addCriterion("PUB_ACCESS_URL not in", values, "pubAccessUrl");
            return (Criteria) this;
        }

        public Criteria andPubAccessUrlBetween(String value1, String value2) {
            addCriterion("PUB_ACCESS_URL between", value1, value2, "pubAccessUrl");
            return (Criteria) this;
        }

        public Criteria andPubAccessUrlNotBetween(String value1, String value2) {
            addCriterion("PUB_ACCESS_URL not between", value1, value2, "pubAccessUrl");
            return (Criteria) this;
        }

        public Criteria andVodAccessUrlIsNull() {
            addCriterion("VOD_ACCESS_URL is null");
            return (Criteria) this;
        }

        public Criteria andVodAccessUrlIsNotNull() {
            addCriterion("VOD_ACCESS_URL is not null");
            return (Criteria) this;
        }

        public Criteria andVodAccessUrlEqualTo(String value) {
            addCriterion("VOD_ACCESS_URL =", value, "vodAccessUrl");
            return (Criteria) this;
        }

        public Criteria andVodAccessUrlNotEqualTo(String value) {
            addCriterion("VOD_ACCESS_URL <>", value, "vodAccessUrl");
            return (Criteria) this;
        }

        public Criteria andVodAccessUrlGreaterThan(String value) {
            addCriterion("VOD_ACCESS_URL >", value, "vodAccessUrl");
            return (Criteria) this;
        }

        public Criteria andVodAccessUrlGreaterThanOrEqualTo(String value) {
            addCriterion("VOD_ACCESS_URL >=", value, "vodAccessUrl");
            return (Criteria) this;
        }

        public Criteria andVodAccessUrlLessThan(String value) {
            addCriterion("VOD_ACCESS_URL <", value, "vodAccessUrl");
            return (Criteria) this;
        }

        public Criteria andVodAccessUrlLessThanOrEqualTo(String value) {
            addCriterion("VOD_ACCESS_URL <=", value, "vodAccessUrl");
            return (Criteria) this;
        }

        public Criteria andVodAccessUrlLike(String value) {
            addCriterion("VOD_ACCESS_URL like", value, "vodAccessUrl");
            return (Criteria) this;
        }

        public Criteria andVodAccessUrlNotLike(String value) {
            addCriterion("VOD_ACCESS_URL not like", value, "vodAccessUrl");
            return (Criteria) this;
        }

        public Criteria andVodAccessUrlIn(List<String> values) {
            addCriterion("VOD_ACCESS_URL in", values, "vodAccessUrl");
            return (Criteria) this;
        }

        public Criteria andVodAccessUrlNotIn(List<String> values) {
            addCriterion("VOD_ACCESS_URL not in", values, "vodAccessUrl");
            return (Criteria) this;
        }

        public Criteria andVodAccessUrlBetween(String value1, String value2) {
            addCriterion("VOD_ACCESS_URL between", value1, value2, "vodAccessUrl");
            return (Criteria) this;
        }

        public Criteria andVodAccessUrlNotBetween(String value1, String value2) {
            addCriterion("VOD_ACCESS_URL not between", value1, value2, "vodAccessUrl");
            return (Criteria) this;
        }

        public Criteria andOptLockIsNull() {
            addCriterion("OPT_LOCK is null");
            return (Criteria) this;
        }

        public Criteria andOptLockIsNotNull() {
            addCriterion("OPT_LOCK is not null");
            return (Criteria) this;
        }

        public Criteria andOptLockEqualTo(Integer value) {
            addCriterion("OPT_LOCK =", value, "optLock");
            return (Criteria) this;
        }

        public Criteria andOptLockNotEqualTo(Integer value) {
            addCriterion("OPT_LOCK <>", value, "optLock");
            return (Criteria) this;
        }

        public Criteria andOptLockGreaterThan(Integer value) {
            addCriterion("OPT_LOCK >", value, "optLock");
            return (Criteria) this;
        }

        public Criteria andOptLockGreaterThanOrEqualTo(Integer value) {
            addCriterion("OPT_LOCK >=", value, "optLock");
            return (Criteria) this;
        }

        public Criteria andOptLockLessThan(Integer value) {
            addCriterion("OPT_LOCK <", value, "optLock");
            return (Criteria) this;
        }

        public Criteria andOptLockLessThanOrEqualTo(Integer value) {
            addCriterion("OPT_LOCK <=", value, "optLock");
            return (Criteria) this;
        }

        public Criteria andOptLockIn(List<Integer> values) {
            addCriterion("OPT_LOCK in", values, "optLock");
            return (Criteria) this;
        }

        public Criteria andOptLockNotIn(List<Integer> values) {
            addCriterion("OPT_LOCK not in", values, "optLock");
            return (Criteria) this;
        }

        public Criteria andOptLockBetween(Integer value1, Integer value2) {
            addCriterion("OPT_LOCK between", value1, value2, "optLock");
            return (Criteria) this;
        }

        public Criteria andOptLockNotBetween(Integer value1, Integer value2) {
            addCriterion("OPT_LOCK not between", value1, value2, "optLock");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}