package com.ht.court.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CourtCaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COURT_CASE
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COURT_CASE
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COURT_CASE
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE
     *
     * @mbggenerated
     */
    public CourtCaseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COURT_CASE
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCaseNumIsNull() {
            addCriterion("CASE_NUM is null");
            return (Criteria) this;
        }

        public Criteria andCaseNumIsNotNull() {
            addCriterion("CASE_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andCaseNumEqualTo(String value) {
            addCriterion("CASE_NUM =", value, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseNumNotEqualTo(String value) {
            addCriterion("CASE_NUM <>", value, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseNumGreaterThan(String value) {
            addCriterion("CASE_NUM >", value, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseNumGreaterThanOrEqualTo(String value) {
            addCriterion("CASE_NUM >=", value, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseNumLessThan(String value) {
            addCriterion("CASE_NUM <", value, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseNumLessThanOrEqualTo(String value) {
            addCriterion("CASE_NUM <=", value, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseNumLike(String value) {
            addCriterion("CASE_NUM like", value, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseNumNotLike(String value) {
            addCriterion("CASE_NUM not like", value, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseNumIn(List<String> values) {
            addCriterion("CASE_NUM in", values, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseNumNotIn(List<String> values) {
            addCriterion("CASE_NUM not in", values, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseNumBetween(String value1, String value2) {
            addCriterion("CASE_NUM between", value1, value2, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseNumNotBetween(String value1, String value2) {
            addCriterion("CASE_NUM not between", value1, value2, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdIsNull() {
            addCriterion("CASE_TYPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdIsNotNull() {
            addCriterion("CASE_TYPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdEqualTo(String value) {
            addCriterion("CASE_TYPE_ID =", value, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdNotEqualTo(String value) {
            addCriterion("CASE_TYPE_ID <>", value, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdGreaterThan(String value) {
            addCriterion("CASE_TYPE_ID >", value, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("CASE_TYPE_ID >=", value, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdLessThan(String value) {
            addCriterion("CASE_TYPE_ID <", value, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdLessThanOrEqualTo(String value) {
            addCriterion("CASE_TYPE_ID <=", value, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdLike(String value) {
            addCriterion("CASE_TYPE_ID like", value, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdNotLike(String value) {
            addCriterion("CASE_TYPE_ID not like", value, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdIn(List<String> values) {
            addCriterion("CASE_TYPE_ID in", values, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdNotIn(List<String> values) {
            addCriterion("CASE_TYPE_ID not in", values, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdBetween(String value1, String value2) {
            addCriterion("CASE_TYPE_ID between", value1, value2, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdNotBetween(String value1, String value2) {
            addCriterion("CASE_TYPE_ID not between", value1, value2, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameIsNull() {
            addCriterion("CASE_TYPE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameIsNotNull() {
            addCriterion("CASE_TYPE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameEqualTo(String value) {
            addCriterion("CASE_TYPE_NAME =", value, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameNotEqualTo(String value) {
            addCriterion("CASE_TYPE_NAME <>", value, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameGreaterThan(String value) {
            addCriterion("CASE_TYPE_NAME >", value, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("CASE_TYPE_NAME >=", value, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameLessThan(String value) {
            addCriterion("CASE_TYPE_NAME <", value, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameLessThanOrEqualTo(String value) {
            addCriterion("CASE_TYPE_NAME <=", value, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameLike(String value) {
            addCriterion("CASE_TYPE_NAME like", value, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameNotLike(String value) {
            addCriterion("CASE_TYPE_NAME not like", value, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameIn(List<String> values) {
            addCriterion("CASE_TYPE_NAME in", values, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameNotIn(List<String> values) {
            addCriterion("CASE_TYPE_NAME not in", values, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameBetween(String value1, String value2) {
            addCriterion("CASE_TYPE_NAME between", value1, value2, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameNotBetween(String value1, String value2) {
            addCriterion("CASE_TYPE_NAME not between", value1, value2, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseNameIsNull() {
            addCriterion("CASE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCaseNameIsNotNull() {
            addCriterion("CASE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCaseNameEqualTo(String value) {
            addCriterion("CASE_NAME =", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameNotEqualTo(String value) {
            addCriterion("CASE_NAME <>", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameGreaterThan(String value) {
            addCriterion("CASE_NAME >", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameGreaterThanOrEqualTo(String value) {
            addCriterion("CASE_NAME >=", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameLessThan(String value) {
            addCriterion("CASE_NAME <", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameLessThanOrEqualTo(String value) {
            addCriterion("CASE_NAME <=", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameLike(String value) {
            addCriterion("CASE_NAME like", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameNotLike(String value) {
            addCriterion("CASE_NAME not like", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameIn(List<String> values) {
            addCriterion("CASE_NAME in", values, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameNotIn(List<String> values) {
            addCriterion("CASE_NAME not in", values, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameBetween(String value1, String value2) {
            addCriterion("CASE_NAME between", value1, value2, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameNotBetween(String value1, String value2) {
            addCriterion("CASE_NAME not between", value1, value2, "caseName");
            return (Criteria) this;
        }

        public Criteria andAccuserIsNull() {
            addCriterion("ACCUSER is null");
            return (Criteria) this;
        }

        public Criteria andAccuserIsNotNull() {
            addCriterion("ACCUSER is not null");
            return (Criteria) this;
        }

        public Criteria andAccuserEqualTo(String value) {
            addCriterion("ACCUSER =", value, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserNotEqualTo(String value) {
            addCriterion("ACCUSER <>", value, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserGreaterThan(String value) {
            addCriterion("ACCUSER >", value, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserGreaterThanOrEqualTo(String value) {
            addCriterion("ACCUSER >=", value, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserLessThan(String value) {
            addCriterion("ACCUSER <", value, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserLessThanOrEqualTo(String value) {
            addCriterion("ACCUSER <=", value, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserLike(String value) {
            addCriterion("ACCUSER like", value, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserNotLike(String value) {
            addCriterion("ACCUSER not like", value, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserIn(List<String> values) {
            addCriterion("ACCUSER in", values, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserNotIn(List<String> values) {
            addCriterion("ACCUSER not in", values, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserBetween(String value1, String value2) {
            addCriterion("ACCUSER between", value1, value2, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserNotBetween(String value1, String value2) {
            addCriterion("ACCUSER not between", value1, value2, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerIsNull() {
            addCriterion("ACCUSER_LAWER is null");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerIsNotNull() {
            addCriterion("ACCUSER_LAWER is not null");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerEqualTo(String value) {
            addCriterion("ACCUSER_LAWER =", value, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerNotEqualTo(String value) {
            addCriterion("ACCUSER_LAWER <>", value, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerGreaterThan(String value) {
            addCriterion("ACCUSER_LAWER >", value, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerGreaterThanOrEqualTo(String value) {
            addCriterion("ACCUSER_LAWER >=", value, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerLessThan(String value) {
            addCriterion("ACCUSER_LAWER <", value, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerLessThanOrEqualTo(String value) {
            addCriterion("ACCUSER_LAWER <=", value, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerLike(String value) {
            addCriterion("ACCUSER_LAWER like", value, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerNotLike(String value) {
            addCriterion("ACCUSER_LAWER not like", value, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerIn(List<String> values) {
            addCriterion("ACCUSER_LAWER in", values, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerNotIn(List<String> values) {
            addCriterion("ACCUSER_LAWER not in", values, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerBetween(String value1, String value2) {
            addCriterion("ACCUSER_LAWER between", value1, value2, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerNotBetween(String value1, String value2) {
            addCriterion("ACCUSER_LAWER not between", value1, value2, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccusedIsNull() {
            addCriterion("ACCUSED is null");
            return (Criteria) this;
        }

        public Criteria andAccusedIsNotNull() {
            addCriterion("ACCUSED is not null");
            return (Criteria) this;
        }

        public Criteria andAccusedEqualTo(String value) {
            addCriterion("ACCUSED =", value, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedNotEqualTo(String value) {
            addCriterion("ACCUSED <>", value, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedGreaterThan(String value) {
            addCriterion("ACCUSED >", value, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedGreaterThanOrEqualTo(String value) {
            addCriterion("ACCUSED >=", value, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedLessThan(String value) {
            addCriterion("ACCUSED <", value, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedLessThanOrEqualTo(String value) {
            addCriterion("ACCUSED <=", value, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedLike(String value) {
            addCriterion("ACCUSED like", value, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedNotLike(String value) {
            addCriterion("ACCUSED not like", value, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedIn(List<String> values) {
            addCriterion("ACCUSED in", values, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedNotIn(List<String> values) {
            addCriterion("ACCUSED not in", values, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedBetween(String value1, String value2) {
            addCriterion("ACCUSED between", value1, value2, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedNotBetween(String value1, String value2) {
            addCriterion("ACCUSED not between", value1, value2, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedLawerIsNull() {
            addCriterion("ACCUSED_LAWER is null");
            return (Criteria) this;
        }

        public Criteria andAccusedLawerIsNotNull() {
            addCriterion("ACCUSED_LAWER is not null");
            return (Criteria) this;
        }

        public Criteria andAccusedLawerEqualTo(String value) {
            addCriterion("ACCUSED_LAWER =", value, "accusedLawer");
            return (Criteria) this;
        }

        public Criteria andAccusedLawerNotEqualTo(String value) {
            addCriterion("ACCUSED_LAWER <>", value, "accusedLawer");
            return (Criteria) this;
        }

        public Criteria andAccusedLawerGreaterThan(String value) {
            addCriterion("ACCUSED_LAWER >", value, "accusedLawer");
            return (Criteria) this;
        }

        public Criteria andAccusedLawerGreaterThanOrEqualTo(String value) {
            addCriterion("ACCUSED_LAWER >=", value, "accusedLawer");
            return (Criteria) this;
        }

        public Criteria andAccusedLawerLessThan(String value) {
            addCriterion("ACCUSED_LAWER <", value, "accusedLawer");
            return (Criteria) this;
        }

        public Criteria andAccusedLawerLessThanOrEqualTo(String value) {
            addCriterion("ACCUSED_LAWER <=", value, "accusedLawer");
            return (Criteria) this;
        }

        public Criteria andAccusedLawerLike(String value) {
            addCriterion("ACCUSED_LAWER like", value, "accusedLawer");
            return (Criteria) this;
        }

        public Criteria andAccusedLawerNotLike(String value) {
            addCriterion("ACCUSED_LAWER not like", value, "accusedLawer");
            return (Criteria) this;
        }

        public Criteria andAccusedLawerIn(List<String> values) {
            addCriterion("ACCUSED_LAWER in", values, "accusedLawer");
            return (Criteria) this;
        }

        public Criteria andAccusedLawerNotIn(List<String> values) {
            addCriterion("ACCUSED_LAWER not in", values, "accusedLawer");
            return (Criteria) this;
        }

        public Criteria andAccusedLawerBetween(String value1, String value2) {
            addCriterion("ACCUSED_LAWER between", value1, value2, "accusedLawer");
            return (Criteria) this;
        }

        public Criteria andAccusedLawerNotBetween(String value1, String value2) {
            addCriterion("ACCUSED_LAWER not between", value1, value2, "accusedLawer");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIsNull() {
            addCriterion("REGISTER_TIME is null");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIsNotNull() {
            addCriterion("REGISTER_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeEqualTo(Date value) {
            addCriterion("REGISTER_TIME =", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotEqualTo(Date value) {
            addCriterion("REGISTER_TIME <>", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeGreaterThan(Date value) {
            addCriterion("REGISTER_TIME >", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REGISTER_TIME >=", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeLessThan(Date value) {
            addCriterion("REGISTER_TIME <", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeLessThanOrEqualTo(Date value) {
            addCriterion("REGISTER_TIME <=", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIn(List<Date> values) {
            addCriterion("REGISTER_TIME in", values, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotIn(List<Date> values) {
            addCriterion("REGISTER_TIME not in", values, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeBetween(Date value1, Date value2) {
            addCriterion("REGISTER_TIME between", value1, value2, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotBetween(Date value1, Date value2) {
            addCriterion("REGISTER_TIME not between", value1, value2, "registerTime");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("DEL_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("DEL_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Boolean value) {
            addCriterion("DEL_FLAG =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Boolean value) {
            addCriterion("DEL_FLAG <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Boolean value) {
            addCriterion("DEL_FLAG >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("DEL_FLAG >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Boolean value) {
            addCriterion("DEL_FLAG <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("DEL_FLAG <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Boolean> values) {
            addCriterion("DEL_FLAG in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Boolean> values) {
            addCriterion("DEL_FLAG not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("DEL_FLAG between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("DEL_FLAG not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("CREATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("CREATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("CREATE_USER_ID =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("CREATE_USER_ID <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("CREATE_USER_ID >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_ID >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("CREATE_USER_ID <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_ID <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("CREATE_USER_ID like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("CREATE_USER_ID not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("CREATE_USER_ID in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("CREATE_USER_ID not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("CREATE_USER_ID between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER_ID not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("UPDATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("UPDATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("UPDATE_USER =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("UPDATE_USER <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("UPDATE_USER >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("UPDATE_USER <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("UPDATE_USER like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("UPDATE_USER not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("UPDATE_USER in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("UPDATE_USER not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("UPDATE_USER between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("UPDATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("UPDATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("UPDATE_USER_ID =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("UPDATE_USER_ID >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("UPDATE_USER_ID <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("UPDATE_USER_ID like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("UPDATE_USER_ID not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("UPDATE_USER_ID in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("UPDATE_USER_ID not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdIsNull() {
            addCriterion("ROOT_ORG_ID is null");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdIsNotNull() {
            addCriterion("ROOT_ORG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdEqualTo(String value) {
            addCriterion("ROOT_ORG_ID =", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdNotEqualTo(String value) {
            addCriterion("ROOT_ORG_ID <>", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdGreaterThan(String value) {
            addCriterion("ROOT_ORG_ID >", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdGreaterThanOrEqualTo(String value) {
            addCriterion("ROOT_ORG_ID >=", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdLessThan(String value) {
            addCriterion("ROOT_ORG_ID <", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdLessThanOrEqualTo(String value) {
            addCriterion("ROOT_ORG_ID <=", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdLike(String value) {
            addCriterion("ROOT_ORG_ID like", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdNotLike(String value) {
            addCriterion("ROOT_ORG_ID not like", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdIn(List<String> values) {
            addCriterion("ROOT_ORG_ID in", values, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdNotIn(List<String> values) {
            addCriterion("ROOT_ORG_ID not in", values, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdBetween(String value1, String value2) {
            addCriterion("ROOT_ORG_ID between", value1, value2, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdNotBetween(String value1, String value2) {
            addCriterion("ROOT_ORG_ID not between", value1, value2, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNull() {
            addCriterion("ORG_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNotNull() {
            addCriterion("ORG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrgIdEqualTo(String value) {
            addCriterion("ORG_ID =", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotEqualTo(String value) {
            addCriterion("ORG_ID <>", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThan(String value) {
            addCriterion("ORG_ID >", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_ID >=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThan(String value) {
            addCriterion("ORG_ID <", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThanOrEqualTo(String value) {
            addCriterion("ORG_ID <=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLike(String value) {
            addCriterion("ORG_ID like", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotLike(String value) {
            addCriterion("ORG_ID not like", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdIn(List<String> values) {
            addCriterion("COURT_ID in", values, "courtId");
//            addCriterion("ORG_ID in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotIn(List<String> values) {
            addCriterion("ORG_ID not in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdBetween(String value1, String value2) {
            addCriterion("ORG_ID between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotBetween(String value1, String value2) {
            addCriterion("ORG_ID not between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andOptLockIsNull() {
            addCriterion("OPT_LOCK is null");
            return (Criteria) this;
        }

        public Criteria andOptLockIsNotNull() {
            addCriterion("OPT_LOCK is not null");
            return (Criteria) this;
        }

        public Criteria andOptLockEqualTo(Integer value) {
            addCriterion("OPT_LOCK =", value, "optLock");
            return (Criteria) this;
        }

        public Criteria andOptLockNotEqualTo(Integer value) {
            addCriterion("OPT_LOCK <>", value, "optLock");
            return (Criteria) this;
        }

        public Criteria andOptLockGreaterThan(Integer value) {
            addCriterion("OPT_LOCK >", value, "optLock");
            return (Criteria) this;
        }

        public Criteria andOptLockGreaterThanOrEqualTo(Integer value) {
            addCriterion("OPT_LOCK >=", value, "optLock");
            return (Criteria) this;
        }

        public Criteria andOptLockLessThan(Integer value) {
            addCriterion("OPT_LOCK <", value, "optLock");
            return (Criteria) this;
        }

        public Criteria andOptLockLessThanOrEqualTo(Integer value) {
            addCriterion("OPT_LOCK <=", value, "optLock");
            return (Criteria) this;
        }

        public Criteria andOptLockIn(List<Integer> values) {
            addCriterion("OPT_LOCK in", values, "optLock");
            return (Criteria) this;
        }

        public Criteria andOptLockNotIn(List<Integer> values) {
            addCriterion("OPT_LOCK not in", values, "optLock");
            return (Criteria) this;
        }

        public Criteria andOptLockBetween(Integer value1, Integer value2) {
            addCriterion("OPT_LOCK between", value1, value2, "optLock");
            return (Criteria) this;
        }

        public Criteria andOptLockNotBetween(Integer value1, Integer value2) {
            addCriterion("OPT_LOCK not between", value1, value2, "optLock");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COURT_CASE
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COURT_CASE
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}