package com.ht.court.model;

public class CourtCaseWithBLOBs extends CourtCase {
  
	private static final long serialVersionUID = -718671849299564753L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE.CASE_DESC
     *  案件详细
     * @mbggenerated
     */
    private String caseDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_CASE.PARTY
     *   当事人信息
     * @mbggenerated
     */
    private String party;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE.CASE_DESC
     *
     * @return the value of COURT_CASE.CASE_DESC
     *
     * @mbggenerated
     */
    public String getCaseDesc() {
        return caseDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE.CASE_DESC
     *
     * @param caseDesc the value for COURT_CASE.CASE_DESC
     *
     * @mbggenerated
     */
    public void setCaseDesc(String caseDesc) {
        this.caseDesc = caseDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_CASE.PARTY
     *
     * @return the value of COURT_CASE.PARTY
     *
     * @mbggenerated
     */
    public String getParty() {
        return party;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_CASE.PARTY
     *
     * @param party the value for COURT_CASE.PARTY
     *
     * @mbggenerated
     */
    public void setParty(String party) {
        this.party = party;
    }
}