package com.fx.oss.vod.model;

public class CourtLiveVodWithBLOBs extends CourtLiveVod {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_LIVE_VOD.CASE_DESC
     *
     * @mbggenerated
     */
    private String caseDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COURT_LIVE_VOD.PARTY
     *
     * @mbggenerated
     */
    private String party;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_LIVE_VOD.CASE_DESC
     *
     * @return the value of COURT_LIVE_VOD.CASE_DESC
     *
     * @mbggenerated
     */
    public String getCaseDesc() {
        return caseDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_LIVE_VOD.CASE_DESC
     *
     * @param caseDesc the value for COURT_LIVE_VOD.CASE_DESC
     *
     * @mbggenerated
     */
    public void setCaseDesc(String caseDesc) {
        this.caseDesc = caseDesc == null ? null : caseDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COURT_LIVE_VOD.PARTY
     *
     * @return the value of COURT_LIVE_VOD.PARTY
     *
     * @mbggenerated
     */
    public String getParty() {
        return party;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COURT_LIVE_VOD.PARTY
     *
     * @param party the value for COURT_LIVE_VOD.PARTY
     *
     * @mbggenerated
     */
    public void setParty(String party) {
        this.party = party == null ? null : party.trim();
    }
}