package com.fx.oss.vod.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CourtLiveVodExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    public CourtLiveVodExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCaseNumIsNull() {
            addCriterion("CASE_NUM is null");
            return (Criteria) this;
        }

        public Criteria andCaseNumIsNotNull() {
            addCriterion("CASE_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andCaseNumEqualTo(String value) {
            addCriterion("CASE_NUM =", value, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseNumNotEqualTo(String value) {
            addCriterion("CASE_NUM <>", value, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseNumGreaterThan(String value) {
            addCriterion("CASE_NUM >", value, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseNumGreaterThanOrEqualTo(String value) {
            addCriterion("CASE_NUM >=", value, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseNumLessThan(String value) {
            addCriterion("CASE_NUM <", value, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseNumLessThanOrEqualTo(String value) {
            addCriterion("CASE_NUM <=", value, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseNumLike(String value) {
            addCriterion("CASE_NUM like", value, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseNumNotLike(String value) {
            addCriterion("CASE_NUM not like", value, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseNumIn(List<String> values) {
            addCriterion("CASE_NUM in", values, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseNumNotIn(List<String> values) {
            addCriterion("CASE_NUM not in", values, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseNumBetween(String value1, String value2) {
            addCriterion("CASE_NUM between", value1, value2, "caseNum");
            return (Criteria) this;
        }

        public Criteria andCaseNumNotBetween(String value1, String value2) {
            addCriterion("CASE_NUM not between", value1, value2, "caseNum");
            return (Criteria) this;
        }

        public Criteria andParentCourtIdIsNull() {
            addCriterion("PARENT_COURT_ID is null");
            return (Criteria) this;
        }

        public Criteria andParentCourtIdIsNotNull() {
            addCriterion("PARENT_COURT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andParentCourtIdEqualTo(String value) {
            addCriterion("PARENT_COURT_ID =", value, "parentCourtId");
            return (Criteria) this;
        }

        public Criteria andParentCourtIdNotEqualTo(String value) {
            addCriterion("PARENT_COURT_ID <>", value, "parentCourtId");
            return (Criteria) this;
        }

        public Criteria andParentCourtIdGreaterThan(String value) {
            addCriterion("PARENT_COURT_ID >", value, "parentCourtId");
            return (Criteria) this;
        }

        public Criteria andParentCourtIdGreaterThanOrEqualTo(String value) {
            addCriterion("PARENT_COURT_ID >=", value, "parentCourtId");
            return (Criteria) this;
        }

        public Criteria andParentCourtIdLessThan(String value) {
            addCriterion("PARENT_COURT_ID <", value, "parentCourtId");
            return (Criteria) this;
        }

        public Criteria andParentCourtIdLessThanOrEqualTo(String value) {
            addCriterion("PARENT_COURT_ID <=", value, "parentCourtId");
            return (Criteria) this;
        }

        public Criteria andParentCourtIdLike(String value) {
            addCriterion("PARENT_COURT_ID like", value, "parentCourtId");
            return (Criteria) this;
        }

        public Criteria andParentCourtIdNotLike(String value) {
            addCriterion("PARENT_COURT_ID not like", value, "parentCourtId");
            return (Criteria) this;
        }

        public Criteria andParentCourtIdIn(List<String> values) {
            addCriterion("PARENT_COURT_ID in", values, "parentCourtId");
            return (Criteria) this;
        }

        public Criteria andParentCourtIdNotIn(List<String> values) {
            addCriterion("PARENT_COURT_ID not in", values, "parentCourtId");
            return (Criteria) this;
        }

        public Criteria andParentCourtIdBetween(String value1, String value2) {
            addCriterion("PARENT_COURT_ID between", value1, value2, "parentCourtId");
            return (Criteria) this;
        }

        public Criteria andParentCourtIdNotBetween(String value1, String value2) {
            addCriterion("PARENT_COURT_ID not between", value1, value2, "parentCourtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdIsNull() {
            addCriterion("COURT_ID is null");
            return (Criteria) this;
        }

        public Criteria andCourtIdIsNotNull() {
            addCriterion("COURT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCourtIdEqualTo(String value) {
            addCriterion("COURT_ID =", value, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdNotEqualTo(String value) {
            addCriterion("COURT_ID <>", value, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdGreaterThan(String value) {
            addCriterion("COURT_ID >", value, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdGreaterThanOrEqualTo(String value) {
            addCriterion("COURT_ID >=", value, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdLessThan(String value) {
            addCriterion("COURT_ID <", value, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdLessThanOrEqualTo(String value) {
            addCriterion("COURT_ID <=", value, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdLike(String value) {
            addCriterion("COURT_ID like", value, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdNotLike(String value) {
            addCriterion("COURT_ID not like", value, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdIn(List<String> values) {
            addCriterion("COURT_ID in", values, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdNotIn(List<String> values) {
            addCriterion("COURT_ID not in", values, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdBetween(String value1, String value2) {
            addCriterion("COURT_ID between", value1, value2, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtIdNotBetween(String value1, String value2) {
            addCriterion("COURT_ID not between", value1, value2, "courtId");
            return (Criteria) this;
        }

        public Criteria andCourtNameIsNull() {
            addCriterion("COURT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCourtNameIsNotNull() {
            addCriterion("COURT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCourtNameEqualTo(String value) {
            addCriterion("COURT_NAME =", value, "courtName");
            return (Criteria) this;
        }

        public Criteria andCourtNameNotEqualTo(String value) {
            addCriterion("COURT_NAME <>", value, "courtName");
            return (Criteria) this;
        }

        public Criteria andCourtNameGreaterThan(String value) {
            addCriterion("COURT_NAME >", value, "courtName");
            return (Criteria) this;
        }

        public Criteria andCourtNameGreaterThanOrEqualTo(String value) {
            addCriterion("COURT_NAME >=", value, "courtName");
            return (Criteria) this;
        }

        public Criteria andCourtNameLessThan(String value) {
            addCriterion("COURT_NAME <", value, "courtName");
            return (Criteria) this;
        }

        public Criteria andCourtNameLessThanOrEqualTo(String value) {
            addCriterion("COURT_NAME <=", value, "courtName");
            return (Criteria) this;
        }

        public Criteria andCourtNameLike(String value) {
            addCriterion("COURT_NAME like", value, "courtName");
            return (Criteria) this;
        }

        public Criteria andCourtNameNotLike(String value) {
            addCriterion("COURT_NAME not like", value, "courtName");
            return (Criteria) this;
        }

        public Criteria andCourtNameIn(List<String> values) {
            addCriterion("COURT_NAME in", values, "courtName");
            return (Criteria) this;
        }

        public Criteria andCourtNameNotIn(List<String> values) {
            addCriterion("COURT_NAME not in", values, "courtName");
            return (Criteria) this;
        }

        public Criteria andCourtNameBetween(String value1, String value2) {
            addCriterion("COURT_NAME between", value1, value2, "courtName");
            return (Criteria) this;
        }

        public Criteria andCourtNameNotBetween(String value1, String value2) {
            addCriterion("COURT_NAME not between", value1, value2, "courtName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdIsNull() {
            addCriterion("COURT_ROOM_ID is null");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdIsNotNull() {
            addCriterion("COURT_ROOM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdEqualTo(String value) {
            addCriterion("COURT_ROOM_ID =", value, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdNotEqualTo(String value) {
            addCriterion("COURT_ROOM_ID <>", value, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdGreaterThan(String value) {
            addCriterion("COURT_ROOM_ID >", value, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdGreaterThanOrEqualTo(String value) {
            addCriterion("COURT_ROOM_ID >=", value, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdLessThan(String value) {
            addCriterion("COURT_ROOM_ID <", value, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdLessThanOrEqualTo(String value) {
            addCriterion("COURT_ROOM_ID <=", value, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdLike(String value) {
            addCriterion("COURT_ROOM_ID like", value, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdNotLike(String value) {
            addCriterion("COURT_ROOM_ID not like", value, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdIn(List<String> values) {
            addCriterion("COURT_ROOM_ID in", values, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdNotIn(List<String> values) {
            addCriterion("COURT_ROOM_ID not in", values, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdBetween(String value1, String value2) {
            addCriterion("COURT_ROOM_ID between", value1, value2, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomIdNotBetween(String value1, String value2) {
            addCriterion("COURT_ROOM_ID not between", value1, value2, "courtRoomId");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameIsNull() {
            addCriterion("COURT_ROOM_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameIsNotNull() {
            addCriterion("COURT_ROOM_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameEqualTo(String value) {
            addCriterion("COURT_ROOM_NAME =", value, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameNotEqualTo(String value) {
            addCriterion("COURT_ROOM_NAME <>", value, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameGreaterThan(String value) {
            addCriterion("COURT_ROOM_NAME >", value, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameGreaterThanOrEqualTo(String value) {
            addCriterion("COURT_ROOM_NAME >=", value, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameLessThan(String value) {
            addCriterion("COURT_ROOM_NAME <", value, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameLessThanOrEqualTo(String value) {
            addCriterion("COURT_ROOM_NAME <=", value, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameLike(String value) {
            addCriterion("COURT_ROOM_NAME like", value, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameNotLike(String value) {
            addCriterion("COURT_ROOM_NAME not like", value, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameIn(List<String> values) {
            addCriterion("COURT_ROOM_NAME in", values, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameNotIn(List<String> values) {
            addCriterion("COURT_ROOM_NAME not in", values, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameBetween(String value1, String value2) {
            addCriterion("COURT_ROOM_NAME between", value1, value2, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andCourtRoomNameNotBetween(String value1, String value2) {
            addCriterion("COURT_ROOM_NAME not between", value1, value2, "courtRoomName");
            return (Criteria) this;
        }

        public Criteria andJudgeIdIsNull() {
            addCriterion("JUDGE_ID is null");
            return (Criteria) this;
        }

        public Criteria andJudgeIdIsNotNull() {
            addCriterion("JUDGE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andJudgeIdEqualTo(String value) {
            addCriterion("JUDGE_ID =", value, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdNotEqualTo(String value) {
            addCriterion("JUDGE_ID <>", value, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdGreaterThan(String value) {
            addCriterion("JUDGE_ID >", value, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdGreaterThanOrEqualTo(String value) {
            addCriterion("JUDGE_ID >=", value, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdLessThan(String value) {
            addCriterion("JUDGE_ID <", value, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdLessThanOrEqualTo(String value) {
            addCriterion("JUDGE_ID <=", value, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdLike(String value) {
            addCriterion("JUDGE_ID like", value, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdNotLike(String value) {
            addCriterion("JUDGE_ID not like", value, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdIn(List<String> values) {
            addCriterion("JUDGE_ID in", values, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdNotIn(List<String> values) {
            addCriterion("JUDGE_ID not in", values, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdBetween(String value1, String value2) {
            addCriterion("JUDGE_ID between", value1, value2, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeIdNotBetween(String value1, String value2) {
            addCriterion("JUDGE_ID not between", value1, value2, "judgeId");
            return (Criteria) this;
        }

        public Criteria andJudgeNameIsNull() {
            addCriterion("JUDGE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andJudgeNameIsNotNull() {
            addCriterion("JUDGE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andJudgeNameEqualTo(String value) {
            addCriterion("JUDGE_NAME =", value, "judgeName");
            return (Criteria) this;
        }

        public Criteria andJudgeNameNotEqualTo(String value) {
            addCriterion("JUDGE_NAME <>", value, "judgeName");
            return (Criteria) this;
        }

        public Criteria andJudgeNameGreaterThan(String value) {
            addCriterion("JUDGE_NAME >", value, "judgeName");
            return (Criteria) this;
        }

        public Criteria andJudgeNameGreaterThanOrEqualTo(String value) {
            addCriterion("JUDGE_NAME >=", value, "judgeName");
            return (Criteria) this;
        }

        public Criteria andJudgeNameLessThan(String value) {
            addCriterion("JUDGE_NAME <", value, "judgeName");
            return (Criteria) this;
        }

        public Criteria andJudgeNameLessThanOrEqualTo(String value) {
            addCriterion("JUDGE_NAME <=", value, "judgeName");
            return (Criteria) this;
        }

        public Criteria andJudgeNameLike(String value) {
            addCriterion("JUDGE_NAME like", value, "judgeName");
            return (Criteria) this;
        }

        public Criteria andJudgeNameNotLike(String value) {
            addCriterion("JUDGE_NAME not like", value, "judgeName");
            return (Criteria) this;
        }

        public Criteria andJudgeNameIn(List<String> values) {
            addCriterion("JUDGE_NAME in", values, "judgeName");
            return (Criteria) this;
        }

        public Criteria andJudgeNameNotIn(List<String> values) {
            addCriterion("JUDGE_NAME not in", values, "judgeName");
            return (Criteria) this;
        }

        public Criteria andJudgeNameBetween(String value1, String value2) {
            addCriterion("JUDGE_NAME between", value1, value2, "judgeName");
            return (Criteria) this;
        }

        public Criteria andJudgeNameNotBetween(String value1, String value2) {
            addCriterion("JUDGE_NAME not between", value1, value2, "judgeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdIsNull() {
            addCriterion("CASE_TYPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdIsNotNull() {
            addCriterion("CASE_TYPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdEqualTo(String value) {
            addCriterion("CASE_TYPE_ID =", value, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdNotEqualTo(String value) {
            addCriterion("CASE_TYPE_ID <>", value, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdGreaterThan(String value) {
            addCriterion("CASE_TYPE_ID >", value, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("CASE_TYPE_ID >=", value, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdLessThan(String value) {
            addCriterion("CASE_TYPE_ID <", value, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdLessThanOrEqualTo(String value) {
            addCriterion("CASE_TYPE_ID <=", value, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdLike(String value) {
            addCriterion("CASE_TYPE_ID like", value, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdNotLike(String value) {
            addCriterion("CASE_TYPE_ID not like", value, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdIn(List<String> values) {
            addCriterion("CASE_TYPE_ID in", values, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdNotIn(List<String> values) {
            addCriterion("CASE_TYPE_ID not in", values, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdBetween(String value1, String value2) {
            addCriterion("CASE_TYPE_ID between", value1, value2, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIdNotBetween(String value1, String value2) {
            addCriterion("CASE_TYPE_ID not between", value1, value2, "caseTypeId");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameIsNull() {
            addCriterion("CASE_TYPE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameIsNotNull() {
            addCriterion("CASE_TYPE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameEqualTo(String value) {
            addCriterion("CASE_TYPE_NAME =", value, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameNotEqualTo(String value) {
            addCriterion("CASE_TYPE_NAME <>", value, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameGreaterThan(String value) {
            addCriterion("CASE_TYPE_NAME >", value, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("CASE_TYPE_NAME >=", value, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameLessThan(String value) {
            addCriterion("CASE_TYPE_NAME <", value, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameLessThanOrEqualTo(String value) {
            addCriterion("CASE_TYPE_NAME <=", value, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameLike(String value) {
            addCriterion("CASE_TYPE_NAME like", value, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameNotLike(String value) {
            addCriterion("CASE_TYPE_NAME not like", value, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameIn(List<String> values) {
            addCriterion("CASE_TYPE_NAME in", values, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameNotIn(List<String> values) {
            addCriterion("CASE_TYPE_NAME not in", values, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameBetween(String value1, String value2) {
            addCriterion("CASE_TYPE_NAME between", value1, value2, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNameNotBetween(String value1, String value2) {
            addCriterion("CASE_TYPE_NAME not between", value1, value2, "caseTypeName");
            return (Criteria) this;
        }

        public Criteria andCaseNameIsNull() {
            addCriterion("CASE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCaseNameIsNotNull() {
            addCriterion("CASE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCaseNameEqualTo(String value) {
            addCriterion("CASE_NAME =", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameNotEqualTo(String value) {
            addCriterion("CASE_NAME <>", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameGreaterThan(String value) {
            addCriterion("CASE_NAME >", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameGreaterThanOrEqualTo(String value) {
            addCriterion("CASE_NAME >=", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameLessThan(String value) {
            addCriterion("CASE_NAME <", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameLessThanOrEqualTo(String value) {
            addCriterion("CASE_NAME <=", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameLike(String value) {
            addCriterion("CASE_NAME like", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameNotLike(String value) {
            addCriterion("CASE_NAME not like", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameIn(List<String> values) {
            addCriterion("CASE_NAME in", values, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameNotIn(List<String> values) {
            addCriterion("CASE_NAME not in", values, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameBetween(String value1, String value2) {
            addCriterion("CASE_NAME between", value1, value2, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameNotBetween(String value1, String value2) {
            addCriterion("CASE_NAME not between", value1, value2, "caseName");
            return (Criteria) this;
        }

        public Criteria andAccuserIsNull() {
            addCriterion("ACCUSER is null");
            return (Criteria) this;
        }

        public Criteria andAccuserIsNotNull() {
            addCriterion("ACCUSER is not null");
            return (Criteria) this;
        }

        public Criteria andAccuserEqualTo(String value) {
            addCriterion("ACCUSER =", value, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserNotEqualTo(String value) {
            addCriterion("ACCUSER <>", value, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserGreaterThan(String value) {
            addCriterion("ACCUSER >", value, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserGreaterThanOrEqualTo(String value) {
            addCriterion("ACCUSER >=", value, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserLessThan(String value) {
            addCriterion("ACCUSER <", value, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserLessThanOrEqualTo(String value) {
            addCriterion("ACCUSER <=", value, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserLike(String value) {
            addCriterion("ACCUSER like", value, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserNotLike(String value) {
            addCriterion("ACCUSER not like", value, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserIn(List<String> values) {
            addCriterion("ACCUSER in", values, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserNotIn(List<String> values) {
            addCriterion("ACCUSER not in", values, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserBetween(String value1, String value2) {
            addCriterion("ACCUSER between", value1, value2, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserNotBetween(String value1, String value2) {
            addCriterion("ACCUSER not between", value1, value2, "accuser");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerIsNull() {
            addCriterion("ACCUSER_LAWER is null");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerIsNotNull() {
            addCriterion("ACCUSER_LAWER is not null");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerEqualTo(String value) {
            addCriterion("ACCUSER_LAWER =", value, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerNotEqualTo(String value) {
            addCriterion("ACCUSER_LAWER <>", value, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerGreaterThan(String value) {
            addCriterion("ACCUSER_LAWER >", value, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerGreaterThanOrEqualTo(String value) {
            addCriterion("ACCUSER_LAWER >=", value, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerLessThan(String value) {
            addCriterion("ACCUSER_LAWER <", value, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerLessThanOrEqualTo(String value) {
            addCriterion("ACCUSER_LAWER <=", value, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerLike(String value) {
            addCriterion("ACCUSER_LAWER like", value, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerNotLike(String value) {
            addCriterion("ACCUSER_LAWER not like", value, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerIn(List<String> values) {
            addCriterion("ACCUSER_LAWER in", values, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerNotIn(List<String> values) {
            addCriterion("ACCUSER_LAWER not in", values, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerBetween(String value1, String value2) {
            addCriterion("ACCUSER_LAWER between", value1, value2, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserLawerNotBetween(String value1, String value2) {
            addCriterion("ACCUSER_LAWER not between", value1, value2, "accuserLawer");
            return (Criteria) this;
        }

        public Criteria andAccusedIsNull() {
            addCriterion("ACCUSED is null");
            return (Criteria) this;
        }

        public Criteria andAccusedIsNotNull() {
            addCriterion("ACCUSED is not null");
            return (Criteria) this;
        }

        public Criteria andAccusedEqualTo(String value) {
            addCriterion("ACCUSED =", value, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedNotEqualTo(String value) {
            addCriterion("ACCUSED <>", value, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedGreaterThan(String value) {
            addCriterion("ACCUSED >", value, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedGreaterThanOrEqualTo(String value) {
            addCriterion("ACCUSED >=", value, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedLessThan(String value) {
            addCriterion("ACCUSED <", value, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedLessThanOrEqualTo(String value) {
            addCriterion("ACCUSED <=", value, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedLike(String value) {
            addCriterion("ACCUSED like", value, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedNotLike(String value) {
            addCriterion("ACCUSED not like", value, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedIn(List<String> values) {
            addCriterion("ACCUSED in", values, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedNotIn(List<String> values) {
            addCriterion("ACCUSED not in", values, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedBetween(String value1, String value2) {
            addCriterion("ACCUSED between", value1, value2, "accused");
            return (Criteria) this;
        }

        public Criteria andAccusedNotBetween(String value1, String value2) {
            addCriterion("ACCUSED not between", value1, value2, "accused");
            return (Criteria) this;
        }

        public Criteria andAccuserdLawerIsNull() {
            addCriterion("ACCUSERD_LAWER is null");
            return (Criteria) this;
        }

        public Criteria andAccuserdLawerIsNotNull() {
            addCriterion("ACCUSERD_LAWER is not null");
            return (Criteria) this;
        }

        public Criteria andAccuserdLawerEqualTo(String value) {
            addCriterion("ACCUSERD_LAWER =", value, "accuserdLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserdLawerNotEqualTo(String value) {
            addCriterion("ACCUSERD_LAWER <>", value, "accuserdLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserdLawerGreaterThan(String value) {
            addCriterion("ACCUSERD_LAWER >", value, "accuserdLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserdLawerGreaterThanOrEqualTo(String value) {
            addCriterion("ACCUSERD_LAWER >=", value, "accuserdLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserdLawerLessThan(String value) {
            addCriterion("ACCUSERD_LAWER <", value, "accuserdLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserdLawerLessThanOrEqualTo(String value) {
            addCriterion("ACCUSERD_LAWER <=", value, "accuserdLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserdLawerLike(String value) {
            addCriterion("ACCUSERD_LAWER like", value, "accuserdLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserdLawerNotLike(String value) {
            addCriterion("ACCUSERD_LAWER not like", value, "accuserdLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserdLawerIn(List<String> values) {
            addCriterion("ACCUSERD_LAWER in", values, "accuserdLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserdLawerNotIn(List<String> values) {
            addCriterion("ACCUSERD_LAWER not in", values, "accuserdLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserdLawerBetween(String value1, String value2) {
            addCriterion("ACCUSERD_LAWER between", value1, value2, "accuserdLawer");
            return (Criteria) this;
        }

        public Criteria andAccuserdLawerNotBetween(String value1, String value2) {
            addCriterion("ACCUSERD_LAWER not between", value1, value2, "accuserdLawer");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIsNull() {
            addCriterion("REGISTER_TIME is null");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIsNotNull() {
            addCriterion("REGISTER_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeEqualTo(Date value) {
            addCriterion("REGISTER_TIME =", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotEqualTo(Date value) {
            addCriterion("REGISTER_TIME <>", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeGreaterThan(Date value) {
            addCriterion("REGISTER_TIME >", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REGISTER_TIME >=", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeLessThan(Date value) {
            addCriterion("REGISTER_TIME <", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeLessThanOrEqualTo(Date value) {
            addCriterion("REGISTER_TIME <=", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIn(List<Date> values) {
            addCriterion("REGISTER_TIME in", values, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotIn(List<Date> values) {
            addCriterion("REGISTER_TIME not in", values, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeBetween(Date value1, Date value2) {
            addCriterion("REGISTER_TIME between", value1, value2, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotBetween(Date value1, Date value2) {
            addCriterion("REGISTER_TIME not between", value1, value2, "registerTime");
            return (Criteria) this;
        }

        public Criteria andLiveUrlIsNull() {
            addCriterion("LIVE_URL is null");
            return (Criteria) this;
        }

        public Criteria andLiveUrlIsNotNull() {
            addCriterion("LIVE_URL is not null");
            return (Criteria) this;
        }

        public Criteria andLiveUrlEqualTo(String value) {
            addCriterion("LIVE_URL =", value, "liveUrl");
            return (Criteria) this;
        }

        public Criteria andLiveUrlNotEqualTo(String value) {
            addCriterion("LIVE_URL <>", value, "liveUrl");
            return (Criteria) this;
        }

        public Criteria andLiveUrlGreaterThan(String value) {
            addCriterion("LIVE_URL >", value, "liveUrl");
            return (Criteria) this;
        }

        public Criteria andLiveUrlGreaterThanOrEqualTo(String value) {
            addCriterion("LIVE_URL >=", value, "liveUrl");
            return (Criteria) this;
        }

        public Criteria andLiveUrlLessThan(String value) {
            addCriterion("LIVE_URL <", value, "liveUrl");
            return (Criteria) this;
        }

        public Criteria andLiveUrlLessThanOrEqualTo(String value) {
            addCriterion("LIVE_URL <=", value, "liveUrl");
            return (Criteria) this;
        }

        public Criteria andLiveUrlLike(String value) {
            addCriterion("LIVE_URL like", value, "liveUrl");
            return (Criteria) this;
        }

        public Criteria andLiveUrlNotLike(String value) {
            addCriterion("LIVE_URL not like", value, "liveUrl");
            return (Criteria) this;
        }

        public Criteria andLiveUrlIn(List<String> values) {
            addCriterion("LIVE_URL in", values, "liveUrl");
            return (Criteria) this;
        }

        public Criteria andLiveUrlNotIn(List<String> values) {
            addCriterion("LIVE_URL not in", values, "liveUrl");
            return (Criteria) this;
        }

        public Criteria andLiveUrlBetween(String value1, String value2) {
            addCriterion("LIVE_URL between", value1, value2, "liveUrl");
            return (Criteria) this;
        }

        public Criteria andLiveUrlNotBetween(String value1, String value2) {
            addCriterion("LIVE_URL not between", value1, value2, "liveUrl");
            return (Criteria) this;
        }

        public Criteria andVodUrlIsNull() {
            addCriterion("VOD_URL is null");
            return (Criteria) this;
        }

        public Criteria andVodUrlIsNotNull() {
            addCriterion("VOD_URL is not null");
            return (Criteria) this;
        }

        public Criteria andVodUrlEqualTo(String value) {
            addCriterion("VOD_URL =", value, "vodUrl");
            return (Criteria) this;
        }

        public Criteria andVodUrlNotEqualTo(String value) {
            addCriterion("VOD_URL <>", value, "vodUrl");
            return (Criteria) this;
        }

        public Criteria andVodUrlGreaterThan(String value) {
            addCriterion("VOD_URL >", value, "vodUrl");
            return (Criteria) this;
        }

        public Criteria andVodUrlGreaterThanOrEqualTo(String value) {
            addCriterion("VOD_URL >=", value, "vodUrl");
            return (Criteria) this;
        }

        public Criteria andVodUrlLessThan(String value) {
            addCriterion("VOD_URL <", value, "vodUrl");
            return (Criteria) this;
        }

        public Criteria andVodUrlLessThanOrEqualTo(String value) {
            addCriterion("VOD_URL <=", value, "vodUrl");
            return (Criteria) this;
        }

        public Criteria andVodUrlLike(String value) {
            addCriterion("VOD_URL like", value, "vodUrl");
            return (Criteria) this;
        }

        public Criteria andVodUrlNotLike(String value) {
            addCriterion("VOD_URL not like", value, "vodUrl");
            return (Criteria) this;
        }

        public Criteria andVodUrlIn(List<String> values) {
            addCriterion("VOD_URL in", values, "vodUrl");
            return (Criteria) this;
        }

        public Criteria andVodUrlNotIn(List<String> values) {
            addCriterion("VOD_URL not in", values, "vodUrl");
            return (Criteria) this;
        }

        public Criteria andVodUrlBetween(String value1, String value2) {
            addCriterion("VOD_URL between", value1, value2, "vodUrl");
            return (Criteria) this;
        }

        public Criteria andVodUrlNotBetween(String value1, String value2) {
            addCriterion("VOD_URL not between", value1, value2, "vodUrl");
            return (Criteria) this;
        }

        public Criteria andVodFilePathIsNull() {
            addCriterion("VOD_FILE_PATH is null");
            return (Criteria) this;
        }

        public Criteria andVodFilePathIsNotNull() {
            addCriterion("VOD_FILE_PATH is not null");
            return (Criteria) this;
        }

        public Criteria andVodFilePathEqualTo(String value) {
            addCriterion("VOD_FILE_PATH =", value, "vodFilePath");
            return (Criteria) this;
        }

        public Criteria andVodFilePathNotEqualTo(String value) {
            addCriterion("VOD_FILE_PATH <>", value, "vodFilePath");
            return (Criteria) this;
        }

        public Criteria andVodFilePathGreaterThan(String value) {
            addCriterion("VOD_FILE_PATH >", value, "vodFilePath");
            return (Criteria) this;
        }

        public Criteria andVodFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("VOD_FILE_PATH >=", value, "vodFilePath");
            return (Criteria) this;
        }

        public Criteria andVodFilePathLessThan(String value) {
            addCriterion("VOD_FILE_PATH <", value, "vodFilePath");
            return (Criteria) this;
        }

        public Criteria andVodFilePathLessThanOrEqualTo(String value) {
            addCriterion("VOD_FILE_PATH <=", value, "vodFilePath");
            return (Criteria) this;
        }

        public Criteria andVodFilePathLike(String value) {
            addCriterion("VOD_FILE_PATH like", value, "vodFilePath");
            return (Criteria) this;
        }

        public Criteria andVodFilePathNotLike(String value) {
            addCriterion("VOD_FILE_PATH not like", value, "vodFilePath");
            return (Criteria) this;
        }

        public Criteria andVodFilePathIn(List<String> values) {
            addCriterion("VOD_FILE_PATH in", values, "vodFilePath");
            return (Criteria) this;
        }

        public Criteria andVodFilePathNotIn(List<String> values) {
            addCriterion("VOD_FILE_PATH not in", values, "vodFilePath");
            return (Criteria) this;
        }

        public Criteria andVodFilePathBetween(String value1, String value2) {
            addCriterion("VOD_FILE_PATH between", value1, value2, "vodFilePath");
            return (Criteria) this;
        }

        public Criteria andVodFilePathNotBetween(String value1, String value2) {
            addCriterion("VOD_FILE_PATH not between", value1, value2, "vodFilePath");
            return (Criteria) this;
        }

        public Criteria andHearTimeIsNull() {
            addCriterion("HEAR_TIME is null");
            return (Criteria) this;
        }

        public Criteria andHearTimeIsNotNull() {
            addCriterion("HEAR_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andHearTimeEqualTo(Date value) {
            addCriterion("HEAR_TIME =", value, "hearTime");
            return (Criteria) this;
        }

        public Criteria andHearTimeNotEqualTo(Date value) {
            addCriterion("HEAR_TIME <>", value, "hearTime");
            return (Criteria) this;
        }

        public Criteria andHearTimeGreaterThan(Date value) {
            addCriterion("HEAR_TIME >", value, "hearTime");
            return (Criteria) this;
        }

        public Criteria andHearTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("HEAR_TIME >=", value, "hearTime");
            return (Criteria) this;
        }

        public Criteria andHearTimeLessThan(Date value) {
            addCriterion("HEAR_TIME <", value, "hearTime");
            return (Criteria) this;
        }

        public Criteria andHearTimeLessThanOrEqualTo(Date value) {
            addCriterion("HEAR_TIME <=", value, "hearTime");
            return (Criteria) this;
        }

        public Criteria andHearTimeIn(List<Date> values) {
            addCriterion("HEAR_TIME in", values, "hearTime");
            return (Criteria) this;
        }

        public Criteria andHearTimeNotIn(List<Date> values) {
            addCriterion("HEAR_TIME not in", values, "hearTime");
            return (Criteria) this;
        }

        public Criteria andHearTimeBetween(Date value1, Date value2) {
            addCriterion("HEAR_TIME between", value1, value2, "hearTime");
            return (Criteria) this;
        }

        public Criteria andHearTimeNotBetween(Date value1, Date value2) {
            addCriterion("HEAR_TIME not between", value1, value2, "hearTime");
            return (Criteria) this;
        }

        public Criteria andTrailStatusIsNull() {
            addCriterion("TRAIL_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andTrailStatusIsNotNull() {
            addCriterion("TRAIL_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andTrailStatusEqualTo(String value) {
            addCriterion("TRAIL_STATUS =", value, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andTrailStatusNotEqualTo(String value) {
            addCriterion("TRAIL_STATUS <>", value, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andTrailStatusGreaterThan(String value) {
            addCriterion("TRAIL_STATUS >", value, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andTrailStatusGreaterThanOrEqualTo(String value) {
            addCriterion("TRAIL_STATUS >=", value, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andTrailStatusLessThan(String value) {
            addCriterion("TRAIL_STATUS <", value, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andTrailStatusLessThanOrEqualTo(String value) {
            addCriterion("TRAIL_STATUS <=", value, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andTrailStatusLike(String value) {
            addCriterion("TRAIL_STATUS like", value, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andTrailStatusNotLike(String value) {
            addCriterion("TRAIL_STATUS not like", value, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andTrailStatusIn(List<String> values) {
            addCriterion("TRAIL_STATUS in", values, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andTrailStatusNotIn(List<String> values) {
            addCriterion("TRAIL_STATUS not in", values, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andTrailStatusBetween(String value1, String value2) {
            addCriterion("TRAIL_STATUS between", value1, value2, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andTrailStatusNotBetween(String value1, String value2) {
            addCriterion("TRAIL_STATUS not between", value1, value2, "trailStatus");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("DEL_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("DEL_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Byte value) {
            addCriterion("DEL_FLAG =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Byte value) {
            addCriterion("DEL_FLAG <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Byte value) {
            addCriterion("DEL_FLAG >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Byte value) {
            addCriterion("DEL_FLAG >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Byte value) {
            addCriterion("DEL_FLAG <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Byte value) {
            addCriterion("DEL_FLAG <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Byte> values) {
            addCriterion("DEL_FLAG in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Byte> values) {
            addCriterion("DEL_FLAG not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Byte value1, Byte value2) {
            addCriterion("DEL_FLAG between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Byte value1, Byte value2) {
            addCriterion("DEL_FLAG not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("CREATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("CREATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("CREATE_USER_ID =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("CREATE_USER_ID <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("CREATE_USER_ID >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_ID >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("CREATE_USER_ID <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_ID <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("CREATE_USER_ID like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("CREATE_USER_ID not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("CREATE_USER_ID in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("CREATE_USER_ID not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("CREATE_USER_ID between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER_ID not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("UPDATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("UPDATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("UPDATE_USER =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("UPDATE_USER <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("UPDATE_USER >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("UPDATE_USER <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("UPDATE_USER like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("UPDATE_USER not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("UPDATE_USER in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("UPDATE_USER not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("UPDATE_USER between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("UPDATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("UPDATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("UPDATE_USER_ID =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("UPDATE_USER_ID >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("UPDATE_USER_ID <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("UPDATE_USER_ID like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("UPDATE_USER_ID not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("UPDATE_USER_ID in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("UPDATE_USER_ID not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdIsNull() {
            addCriterion("ROOT_ORG_ID is null");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdIsNotNull() {
            addCriterion("ROOT_ORG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdEqualTo(String value) {
            addCriterion("ROOT_ORG_ID =", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdNotEqualTo(String value) {
            addCriterion("ROOT_ORG_ID <>", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdGreaterThan(String value) {
            addCriterion("ROOT_ORG_ID >", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdGreaterThanOrEqualTo(String value) {
            addCriterion("ROOT_ORG_ID >=", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdLessThan(String value) {
            addCriterion("ROOT_ORG_ID <", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdLessThanOrEqualTo(String value) {
            addCriterion("ROOT_ORG_ID <=", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdLike(String value) {
            addCriterion("ROOT_ORG_ID like", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdNotLike(String value) {
            addCriterion("ROOT_ORG_ID not like", value, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdIn(List<String> values) {
            addCriterion("ROOT_ORG_ID in", values, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdNotIn(List<String> values) {
            addCriterion("ROOT_ORG_ID not in", values, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdBetween(String value1, String value2) {
            addCriterion("ROOT_ORG_ID between", value1, value2, "rootOrgId");
            return (Criteria) this;
        }

        public Criteria andRootOrgIdNotBetween(String value1, String value2) {
            addCriterion("ROOT_ORG_ID not between", value1, value2, "rootOrgId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}