package com.fx.oss.vod.persistence;

import com.fx.oss.vod.model.CourtLiveVod;
import com.fx.oss.vod.model.CourtLiveVodExample;
import com.fx.oss.vod.model.CourtLiveVodWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourtLiveVodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    int countByExample(CourtLiveVodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    int deleteByExample(CourtLiveVodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    int insert(CourtLiveVodWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    int insertSelective(CourtLiveVodWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    List<CourtLiveVodWithBLOBs> selectByExampleWithBLOBs(CourtLiveVodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    List<CourtLiveVod> selectByExample(CourtLiveVodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    CourtLiveVodWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CourtLiveVodWithBLOBs record, @Param("example") CourtLiveVodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") CourtLiveVodWithBLOBs record, @Param("example") CourtLiveVodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CourtLiveVod record, @Param("example") CourtLiveVodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CourtLiveVodWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CourtLiveVodWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_LIVE_VOD
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CourtLiveVod record);
    
    /**
     * 分页查询-查询记录数
     */
    int selectTotalPage();
    /**
     * 点播列表分页查询
     * @param begin
     * @param size
     * @return List<CourtLiveVodWithBLOBs>
     */
	List<CourtLiveVodWithBLOBs> getMetaDevByPage(@Param("begin")int begin, @Param("size")int size);

	int getAllMetaDevCount();
	/**
	 * 直播列表
	 * @return
	 */
	List<CourtLiveVodWithBLOBs> selectLiveList();
	
	List<CourtLiveVodWithBLOBs> getCourtLiveVodByCaseNum(@Param("caseNum") String caseNum,@Param("begin")int begin, @Param("size")int size);
}