package com.ht.court.mapper;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ht.court.model.CourtCasePlan;
import com.ht.court.model.CourtCasePlanExample;

public interface CourtCasePlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    int countByExample(CourtCasePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    int deleteByExample(CourtCasePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    int insert(CourtCasePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    int insertSelective(CourtCasePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    List<CourtCasePlan> selectByExample(CourtCasePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    CourtCasePlan selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CourtCasePlan record, @Param("example") CourtCasePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CourtCasePlan record, @Param("example") CourtCasePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CourtCasePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_CASE_PLAN
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CourtCasePlan record);
    
    /**
     *  获取排期，直点播列表数据并分页显示
     * @param List 法院ID集合
     * @param BillboardTime 排期时间
     * @param pubTime  直播时间
     * @param vodTime  点播时间
     * @param begin  开始条数
     * @param size  每页记录条数
     * @return
     */
    List<CourtCasePlan> showCaseAndPlanData
    	(@Param("list") List<String> List, @Param("BillboardTime") Date BillboardTime, @Param("pubTime") Date pubTime, @Param("vodTime") Date vodTime, @Param("begin") int begin, @Param("size") int size);
    /**
     *  根据模糊查询来获得排期，直点播信息列表并分页显示
     * @param List 法院ID集合
     * @param BillboardTime 排期时间
     * @param pubTime  直播时间
     * @param vodTime  点播时间
     * @param caseLikeName  案件模糊条件参数
     * @param begin  开始条数
     * @param size  每页记录条数
     * @param startTime  开始时间
     * @param endTime  结束时间
     * @return
     */
    List<CourtCasePlan> showCaseAndPlanDataByLike
    	(@Param("list") List<String> List, @Param("BillboardTime") Date BillboardTime, @Param("pubTime") Date pubTime, @Param("vodTime") Date vodTime, @Param("caseLikeName") String caseLikeName, @Param("begin") int begin, @Param("size") int size, @Param("startTime") Date startTime, @Param("endTime") Date endTime);
    
    
    
    /**
     *  case 和 plan 表关联，获取案件和排期信息列表并分页显示
     * @param list
     * @param BillboardTime
     * @param pubTime
     * @param vodTime
     * @param begin
     * @param size
     * @return
     */
     List<CourtCasePlan> getAllCaseAndPlan(@Param("list") List<String> list, @Param("BillboardTime") Date BillboardTime, @Param("pubTime") Date pubTime, @Param("vodTime") Date vodTime, @Param("begin") int begin, @Param("size") int size);

     /**
      * 根据排期表获取所有符合条件的信息条数
      * @param paramList
      * @param paramDate1
      * @param paramDate2
      * @param paramDate3
      * @return
      */
     int getCaseAndPlanNum(@Param("list") List<String> list, @Param("BillboardTime") Date BillboardTime, @Param("pubTime") Date pubTime, @Param("vodTime") Date vodTime, @Param("vodSuccessFlag") String vodSuccessFlag);

     /**
      * 根据排期id获取案件和排期信息
      * @param paramString1
      * @param paramString2
      * @return
      */
     CourtCasePlan getCaseMessageByPlanId(@Param("id") String id);

     /**
      * 模糊查询 得到案件和排期的记录条数并分页显示
      * @return
      */
     List<CourtCasePlan> getCaseAndPlanByLike(@Param("list") List<String> list, @Param("BillboardTime") Date BillboardTime, @Param("pubTime") Date pubTime, @Param("vodTime") Date vodTime, @Param("caseLikeName") String caseLikeName, @Param("begin") int begin, @Param("size") int size, @Param("startTime") Date startTime, @Param("endTime") Date endTime);

     /**
      * 模糊查询 得到案件和排期的记录条数
      * @param list
      * @param BillboardTime
      * @param pubTime
      * @param vodTime
      * @param caseLikeName
      * @param startTime
      * @param endTime
      * @return
      */
     int getCaseAndPlanNums(@Param("list") List<String> list, @Param("BillboardTime") Date BillboardTime, @Param("pubTime") Date pubTime, @Param("vodTime") Date vodTime, @Param("caseLikeName") String caseLikeName, @Param("startTime") Date startTime, @Param("endTime") Date endTime);
     
     /**
      * 根据时间获取到点播信息
      * @param vodTime
      * @return
      */
     List<CourtCasePlan> getCaseNumAndStartTime(@Param("vodTime") Date vodTime);

     /**
      *  得到符合直播的信息
      * @return
      */
     List<CourtCasePlan> getliveByTime(@Param("startTime") Date startTime, @Param("endTime") Date endTime);
     
     /**
      *  获取直播预告信息并分页显示
      * @param startTime
      * @param endTime
      * @param begin
      * @param size
      * @return
      */
     List<CourtCasePlan> findLiveBillboard
     	(@Param("startTime") Date startTime, @Param("endTime") Date endTime,@Param("beginTime") Date beginTime, @Param("stopTime") Date stopTime,@Param("caseType") String caseType,@Param("courtName") String courtName,@Param("begin") int begin, @Param("size") int size);
     
     /**
      * 得到直播预告的总记录数
      * @param startTime
      * @param endTime
      * @param begin
      * @param size
      * @return
      */
     int getLiveBillboardNum(@Param("startTime") Date startTime, @Param("endTime") Date endTime,@Param("beginTime") Date beginTime, @Param("stopTime") Date stopTime,@Param("caseType") String caseType,@Param("courtName") String courtName);
     
     /**
      * 
      * @param startTime 庭审直播开始时间。
	  * @param endTime 庭审直播结束时间。
	  * @param courtId 法院id。
	  * @param courtName 法院名称，支持模糊查询。
	  * @param caseName 案件名称，支持模糊查询。
 	  * @param caseType 案件类型。
      * @param begin 开始条数
      * @param size  结束条数
      * @return
      */
     List<CourtCasePlan> findCaseBySearch
     	(@Param("startTime") Date startTime, @Param("endTime") Date endTime,@Param("courtName") String courtName,@Param("caseName") String caseName,@Param("caseType") String caseType,@Param("courtId") String courtId,@Param("trialLevel") String trialLevel,@Param("begin") int begin, @Param("size") int size);
     /**
      *  条件查询案件和排期
      * @param startTime 庭审直播开始时间。
	  * @param endTime 庭审直播结束时间。
	  * @param courtId 法院id。
	  * @param courtName 法院名称，支持模糊查询。
	  * @param caseName 案件名称，支持模糊查询。
 	  * @param caseType 案件类型。
      * @return
      */
     int getCaseNumBySearch(@Param("startTime") Date startTime, @Param("endTime") Date endTime,@Param("courtName") String courtName,@Param("caseName") String caseName,@Param("caseType") String caseType,@Param("courtId") String courtId,@Param("trialLevel") String trialLevel);
     
  }