package com.ht.court.mapper;

import com.ht.court.model.CourtTrialRecording;
import com.ht.court.model.CourtTrialRecordingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourtTrialRecordingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_TRIAL_RECORDING
     *
     * @mbggenerated
     */
    int countByExample(CourtTrialRecordingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_TRIAL_RECORDING
     *
     * @mbggenerated
     */
    int deleteByExample(CourtTrialRecordingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_TRIAL_RECORDING
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_TRIAL_RECORDING
     *
     * @mbggenerated
     */
    int insert(CourtTrialRecording record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_TRIAL_RECORDING
     *
     * @mbggenerated
     */
    int insertSelective(CourtTrialRecording record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_TRIAL_RECORDING
     *
     * @mbggenerated
     */
    List<CourtTrialRecording> selectByExampleWithBLOBs(CourtTrialRecordingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_TRIAL_RECORDING
     *
     * @mbggenerated
     */
    List<CourtTrialRecording> selectByExample(CourtTrialRecordingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_TRIAL_RECORDING
     *
     * @mbggenerated
     */
    CourtTrialRecording selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_TRIAL_RECORDING
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CourtTrialRecording record, @Param("example") CourtTrialRecordingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_TRIAL_RECORDING
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") CourtTrialRecording record, @Param("example") CourtTrialRecordingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_TRIAL_RECORDING
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CourtTrialRecording record, @Param("example") CourtTrialRecordingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_TRIAL_RECORDING
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CourtTrialRecording record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_TRIAL_RECORDING
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CourtTrialRecording record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURT_TRIAL_RECORDING
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CourtTrialRecording record);
}